
/* automatically generated by mkdynam.py */
#ifndef ivx11_define_h
#define ivx11_define_h

IVX11EXTERN int *ivdynam__Xdebug ;
IVX11EXTERN XFontStruct * (*ivdynam_XLoadQueryFont) (
    Display*		/* display */,
    _Xconst char*	/* name */
);
IVX11EXTERN XFontStruct * (*ivdynam_XQueryFont) (
    Display*		/* display */,
    XID			/* font_ID */
);
IVX11EXTERN XTimeCoord * (*ivdynam_XGetMotionEvents) (
    Display*		/* display */,
    Window		/* w */,
    Time		/* start */,
    Time		/* stop */,
    int*		/* nevents_return */
);
IVX11EXTERN XModifierKeymap * (*ivdynam_XDeleteModifiermapEntry) (
    XModifierKeymap*	/* modmap */,
#if NeedWidePrototypes
    unsigned int	/* keycode_entry */,
#else
    KeyCode		/* keycode_entry */,
#endif
    int			/* modifier */
);
IVX11EXTERN XModifierKeymap * (*ivdynam_XGetModifierMapping) (
    Display*		/* display */
);
IVX11EXTERN XModifierKeymap * (*ivdynam_XInsertModifiermapEntry) (
    XModifierKeymap*	/* modmap */,
#if NeedWidePrototypes
    unsigned int	/* keycode_entry */,
#else
    KeyCode		/* keycode_entry */,
#endif
    int			/* modifier */
);
IVX11EXTERN XModifierKeymap * (*ivdynam_XNewModifiermap) (
    int			/* max_keys_per_mod */
);
IVX11EXTERN XImage * (*ivdynam_XCreateImage) (
    Display*		/* display */,
    Visual*		/* visual */,
    unsigned int	/* depth */,
    int			/* format */,
    int			/* offset */,
    char*		/* data */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    int			/* bitmap_pad */,
    int			/* bytes_per_line */
);
IVX11EXTERN Status (*ivdynam_XInitImage) (
    XImage*		/* image */
);
IVX11EXTERN XImage * (*ivdynam_XGetImage) (
    Display*		/* display */,
    Drawable		/* d */,
    int			/* x */,
    int			/* y */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    unsigned long	/* plane_mask */,
    int			/* format */
);
IVX11EXTERN XImage * (*ivdynam_XGetSubImage) (
    Display*		/* display */,
    Drawable		/* d */,
    int			/* x */,
    int			/* y */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    unsigned long	/* plane_mask */,
    int			/* format */,
    XImage*		/* dest_image */,
    int			/* dest_x */,
    int			/* dest_y */
);
IVX11EXTERN Display * (*ivdynam_XOpenDisplay) (
    _Xconst char*	/* display_name */
);
IVX11EXTERN void (*ivdynam_XrmInitialize) (
    void
);
IVX11EXTERN char * (*ivdynam_XFetchBytes) (
    Display*		/* display */,
    int*		/* nbytes_return */
);
IVX11EXTERN char * (*ivdynam_XFetchBuffer) (
    Display*		/* display */,
    int*		/* nbytes_return */,
    int			/* buffer */
);
IVX11EXTERN char * (*ivdynam_XGetAtomName) (
    Display*		/* display */,
    Atom		/* atom */
);
IVX11EXTERN Status (*ivdynam_XGetAtomNames) (
    Display*		/* dpy */,
    Atom*		/* atoms */,
    int			/* count */,
    char**		/* names_return */
);
IVX11EXTERN char * (*ivdynam_XGetDefault) (
    Display*		/* display */,
    _Xconst char*	/* program */,
    _Xconst char*	/* option */
);
IVX11EXTERN char * (*ivdynam_XDisplayName) (
    _Xconst char*	/* string */
);
IVX11EXTERN char * (*ivdynam_XKeysymToString) (
    KeySym		/* keysym */
);
typedef int ( * ivdynam_XSynchronize_t (
    Display*		/* display */,
    Bool		/* onoff */
))(
    Display*		/* display */
);
IVX11EXTERN ivdynam_XSynchronize_t* ivdynam_XSynchronize;
typedef int ( * ivdynam_XSetAfterFunction_t (
    Display*		/* display */,
    int (*) (
	     Display*	/* display */
            )		/* procedure */
))(
    Display*		/* display */
);
IVX11EXTERN ivdynam_XSetAfterFunction_t* ivdynam_XSetAfterFunction;
IVX11EXTERN Atom (*ivdynam_XInternAtom) (
    Display*		/* display */,
    _Xconst char*	/* atom_name */,
    Bool		/* only_if_exists */
);
IVX11EXTERN Status (*ivdynam_XInternAtoms) (
    Display*		/* dpy */,
    char**		/* names */,
    int			/* count */,
    Bool		/* onlyIfExists */,
    Atom*		/* atoms_return */
);
IVX11EXTERN Colormap (*ivdynam_XCopyColormapAndFree) (
    Display*		/* display */,
    Colormap		/* colormap */
);
IVX11EXTERN Colormap (*ivdynam_XCreateColormap) (
    Display*		/* display */,
    Window		/* w */,
    Visual*		/* visual */,
    int			/* alloc */
);
IVX11EXTERN Cursor (*ivdynam_XCreatePixmapCursor) (
    Display*		/* display */,
    Pixmap		/* source */,
    Pixmap		/* mask */,
    XColor*		/* foreground_color */,
    XColor*		/* background_color */,
    unsigned int	/* x */,
    unsigned int	/* y */
);
IVX11EXTERN Cursor (*ivdynam_XCreateGlyphCursor) (
    Display*		/* display */,
    Font		/* source_font */,
    Font		/* mask_font */,
    unsigned int	/* source_char */,
    unsigned int	/* mask_char */,
    XColor _Xconst *	/* foreground_color */,
    XColor _Xconst *	/* background_color */
);
IVX11EXTERN Cursor (*ivdynam_XCreateFontCursor) (
    Display*		/* display */,
    unsigned int	/* shape */
);
IVX11EXTERN Font (*ivdynam_XLoadFont) (
    Display*		/* display */,
    _Xconst char*	/* name */
);
IVX11EXTERN GC (*ivdynam_XCreateGC) (
    Display*		/* display */,
    Drawable		/* d */,
    unsigned long	/* valuemask */,
    XGCValues*		/* values */
);
IVX11EXTERN GContext (*ivdynam_XGContextFromGC) (
    GC			/* gc */
);
IVX11EXTERN void (*ivdynam_XFlushGC) (
    Display*		/* display */,
    GC			/* gc */
);
IVX11EXTERN Pixmap (*ivdynam_XCreatePixmap) (
    Display*		/* display */,
    Drawable		/* d */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    unsigned int	/* depth */
);
IVX11EXTERN Pixmap (*ivdynam_XCreateBitmapFromData) (
    Display*		/* display */,
    Drawable		/* d */,
    _Xconst char*	/* data */,
    unsigned int	/* width */,
    unsigned int	/* height */
);
IVX11EXTERN Pixmap (*ivdynam_XCreatePixmapFromBitmapData) (
    Display*		/* display */,
    Drawable		/* d */,
    char*		/* data */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    unsigned long	/* fg */,
    unsigned long	/* bg */,
    unsigned int	/* depth */
);
IVX11EXTERN Window (*ivdynam_XCreateSimpleWindow) (
    Display*		/* display */,
    Window		/* parent */,
    int			/* x */,
    int			/* y */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    unsigned int	/* border_width */,
    unsigned long	/* border */,
    unsigned long	/* background */
);
IVX11EXTERN Window (*ivdynam_XGetSelectionOwner) (
    Display*		/* display */,
    Atom		/* selection */
);
IVX11EXTERN Window (*ivdynam_XCreateWindow) (
    Display*		/* display */,
    Window		/* parent */,
    int			/* x */,
    int			/* y */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    unsigned int	/* border_width */,
    int			/* depth */,
    unsigned int	/* class */,
    Visual*		/* visual */,
    unsigned long	/* valuemask */,
    XSetWindowAttributes*	/* attributes */
);
IVX11EXTERN Colormap * (*ivdynam_XListInstalledColormaps) (
    Display*		/* display */,
    Window		/* w */,
    int*		/* num_return */
);
IVX11EXTERN char ** (*ivdynam_XListFonts) (
    Display*		/* display */,
    _Xconst char*	/* pattern */,
    int			/* maxnames */,
    int*		/* actual_count_return */
);
IVX11EXTERN char ** (*ivdynam_XListFontsWithInfo) (
    Display*		/* display */,
    _Xconst char*	/* pattern */,
    int			/* maxnames */,
    int*		/* count_return */,
    XFontStruct**	/* info_return */
);
IVX11EXTERN char ** (*ivdynam_XGetFontPath) (
    Display*		/* display */,
    int*		/* npaths_return */
);
IVX11EXTERN char ** (*ivdynam_XListExtensions) (
    Display*		/* display */,
    int*		/* nextensions_return */
);
IVX11EXTERN Atom * (*ivdynam_XListProperties) (
    Display*		/* display */,
    Window		/* w */,
    int*		/* num_prop_return */
);
IVX11EXTERN XHostAddress * (*ivdynam_XListHosts) (
    Display*		/* display */,
    int*		/* nhosts_return */,
    Bool*		/* state_return */
);
IVX11EXTERN KeySym (*ivdynam_XLookupKeysym) (
    XKeyEvent*		/* key_event */,
    int			/* index */
);
IVX11EXTERN KeySym * (*ivdynam_XGetKeyboardMapping) (
    Display*		/* display */,
#if NeedWidePrototypes
    unsigned int	/* first_keycode */,
#else
    KeyCode		/* first_keycode */,
#endif
    int			/* keycode_count */,
    int*		/* keysyms_per_keycode_return */
);
IVX11EXTERN KeySym (*ivdynam_XStringToKeysym) (
    _Xconst char*	/* string */
);
IVX11EXTERN long (*ivdynam_XMaxRequestSize) (
    Display*		/* display */
);
IVX11EXTERN long (*ivdynam_XExtendedMaxRequestSize) (
    Display*		/* display */
);
IVX11EXTERN char * (*ivdynam_XResourceManagerString) (
    Display*		/* display */
);
IVX11EXTERN char * (*ivdynam_XScreenResourceString) (
	Screen*		/* screen */
);
IVX11EXTERN unsigned long (*ivdynam_XDisplayMotionBufferSize) (
    Display*		/* display */
);
IVX11EXTERN VisualID (*ivdynam_XVisualIDFromVisual) (
    Visual*		/* visual */
);
IVX11EXTERN Status (*ivdynam_XInitThreads) (
    void
);
IVX11EXTERN void (*ivdynam_XLockDisplay) (
    Display*		/* display */
);
IVX11EXTERN void (*ivdynam_XUnlockDisplay) (
    Display*		/* display */
);
IVX11EXTERN XExtCodes * (*ivdynam_XInitExtension) (
    Display*		/* display */,
    _Xconst char*	/* name */
);
IVX11EXTERN XExtCodes * (*ivdynam_XAddExtension) (
    Display*		/* display */
);
IVX11EXTERN XExtData * (*ivdynam_XFindOnExtensionList) (
    XExtData**		/* structure */,
    int			/* number */
);
IVX11EXTERN XExtData ** (*ivdynam_XEHeadOfExtensionList) (
    XEDataObject	/* object */
);
IVX11EXTERN Window (*ivdynam_XRootWindow) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN Window (*ivdynam_XDefaultRootWindow) (
    Display*		/* display */
);
IVX11EXTERN Window (*ivdynam_XRootWindowOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN Visual * (*ivdynam_XDefaultVisual) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN Visual * (*ivdynam_XDefaultVisualOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN GC (*ivdynam_XDefaultGC) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN GC (*ivdynam_XDefaultGCOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN unsigned long (*ivdynam_XBlackPixel) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN unsigned long (*ivdynam_XWhitePixel) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN unsigned long (*ivdynam_XAllPlanes) (
    void
);
IVX11EXTERN unsigned long (*ivdynam_XBlackPixelOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN unsigned long (*ivdynam_XWhitePixelOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN unsigned long (*ivdynam_XNextRequest) (
    Display*		/* display */
);
IVX11EXTERN unsigned long (*ivdynam_XLastKnownRequestProcessed) (
    Display*		/* display */
);
IVX11EXTERN char * (*ivdynam_XServerVendor) (
    Display*		/* display */
);
IVX11EXTERN char * (*ivdynam_XDisplayString) (
    Display*		/* display */
);
IVX11EXTERN Colormap (*ivdynam_XDefaultColormap) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN Colormap (*ivdynam_XDefaultColormapOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN Display * (*ivdynam_XDisplayOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN Screen * (*ivdynam_XScreenOfDisplay) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN Screen * (*ivdynam_XDefaultScreenOfDisplay) (
    Display*		/* display */
);
IVX11EXTERN long (*ivdynam_XEventMaskOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN int (*ivdynam_XScreenNumberOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN XErrorHandler (*ivdynam_XSetErrorHandler) (
    XErrorHandler	/* handler */
);
IVX11EXTERN XIOErrorHandler (*ivdynam_XSetIOErrorHandler) (
    XIOErrorHandler	/* handler */
);
IVX11EXTERN XPixmapFormatValues * (*ivdynam_XListPixmapFormats) (
    Display*		/* display */,
    int*		/* count_return */
);
IVX11EXTERN int * (*ivdynam_XListDepths) (
    Display*		/* display */,
    int			/* screen_number */,
    int*		/* count_return */
);
IVX11EXTERN Status (*ivdynam_XReconfigureWMWindow) (
    Display*		/* display */,
    Window		/* w */,
    int			/* screen_number */,
    unsigned int	/* mask */,
    XWindowChanges*	/* changes */
);
IVX11EXTERN Status (*ivdynam_XGetWMProtocols) (
    Display*		/* display */,
    Window		/* w */,
    Atom**		/* protocols_return */,
    int*		/* count_return */
);
IVX11EXTERN Status (*ivdynam_XSetWMProtocols) (
    Display*		/* display */,
    Window		/* w */,
    Atom*		/* protocols */,
    int			/* count */
);
IVX11EXTERN Status (*ivdynam_XIconifyWindow) (
    Display*		/* display */,
    Window		/* w */,
    int			/* screen_number */
);
IVX11EXTERN Status (*ivdynam_XWithdrawWindow) (
    Display*		/* display */,
    Window		/* w */,
    int			/* screen_number */
);
IVX11EXTERN Status (*ivdynam_XGetCommand) (
    Display*		/* display */,
    Window		/* w */,
    char***		/* argv_return */,
    int*		/* argc_return */
);
IVX11EXTERN Status (*ivdynam_XGetWMColormapWindows) (
    Display*		/* display */,
    Window		/* w */,
    Window**		/* windows_return */,
    int*		/* count_return */
);
IVX11EXTERN Status (*ivdynam_XSetWMColormapWindows) (
    Display*		/* display */,
    Window		/* w */,
    Window*		/* colormap_windows */,
    int			/* count */
);
IVX11EXTERN void (*ivdynam_XFreeStringList) (
    char**		/* list */
);
IVX11EXTERN int (*ivdynam_XSetTransientForHint) (
    Display*		/* display */,
    Window		/* w */,
    Window		/* prop_window */
);
IVX11EXTERN int (*ivdynam_XActivateScreenSaver) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XAddHost) (
    Display*		/* display */,
    XHostAddress*	/* host */
);
IVX11EXTERN int (*ivdynam_XAddHosts) (
    Display*		/* display */,
    XHostAddress*	/* hosts */,
    int			/* num_hosts */
);
IVX11EXTERN int (*ivdynam_XAddToExtensionList) (
    struct _XExtData**	/* structure */,
    XExtData*		/* ext_data */
);
IVX11EXTERN int (*ivdynam_XAddToSaveSet) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN Status (*ivdynam_XAllocColor) (
    Display*		/* display */,
    Colormap		/* colormap */,
    XColor*		/* screen_in_out */
);
IVX11EXTERN Status (*ivdynam_XAllocColorCells) (
    Display*		/* display */,
    Colormap		/* colormap */,
    Bool	        /* contig */,
    unsigned long*	/* plane_masks_return */,
    unsigned int	/* nplanes */,
    unsigned long*	/* pixels_return */,
    unsigned int 	/* npixels */
);
IVX11EXTERN Status (*ivdynam_XAllocColorPlanes) (
    Display*		/* display */,
    Colormap		/* colormap */,
    Bool		/* contig */,
    unsigned long*	/* pixels_return */,
    int			/* ncolors */,
    int			/* nreds */,
    int			/* ngreens */,
    int			/* nblues */,
    unsigned long*	/* rmask_return */,
    unsigned long*	/* gmask_return */,
    unsigned long*	/* bmask_return */
);
IVX11EXTERN Status (*ivdynam_XAllocNamedColor) (
    Display*		/* display */,
    Colormap		/* colormap */,
    _Xconst char*	/* color_name */,
    XColor*		/* screen_def_return */,
    XColor*		/* exact_def_return */
);
IVX11EXTERN int (*ivdynam_XAllowEvents) (
    Display*		/* display */,
    int			/* event_mode */,
    Time		/* time */
);
IVX11EXTERN int (*ivdynam_XAutoRepeatOff) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XAutoRepeatOn) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XBell) (
    Display*		/* display */,
    int			/* percent */
);
IVX11EXTERN int (*ivdynam_XBitmapBitOrder) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XBitmapPad) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XBitmapUnit) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XCellsOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN int (*ivdynam_XChangeActivePointerGrab) (
    Display*		/* display */,
    unsigned int	/* event_mask */,
    Cursor		/* cursor */,
    Time		/* time */
);
IVX11EXTERN int (*ivdynam_XChangeGC) (
    Display*		/* display */,
    GC			/* gc */,
    unsigned long	/* valuemask */,
    XGCValues*		/* values */
);
IVX11EXTERN int (*ivdynam_XChangeKeyboardControl) (
    Display*		/* display */,
    unsigned long	/* value_mask */,
    XKeyboardControl*	/* values */
);
IVX11EXTERN int (*ivdynam_XChangeKeyboardMapping) (
    Display*		/* display */,
    int			/* first_keycode */,
    int			/* keysyms_per_keycode */,
    KeySym*		/* keysyms */,
    int			/* num_codes */
);
IVX11EXTERN int (*ivdynam_XChangePointerControl) (
    Display*		/* display */,
    Bool		/* do_accel */,
    Bool		/* do_threshold */,
    int			/* accel_numerator */,
    int			/* accel_denominator */,
    int			/* threshold */
);
IVX11EXTERN int (*ivdynam_XChangeProperty) (
    Display*		/* display */,
    Window		/* w */,
    Atom		/* property */,
    Atom		/* type */,
    int			/* format */,
    int			/* mode */,
    _Xconst unsigned char*	/* data */,
    int			/* nelements */
);
IVX11EXTERN int (*ivdynam_XChangeSaveSet) (
    Display*		/* display */,
    Window		/* w */,
    int			/* change_mode */
);
IVX11EXTERN int (*ivdynam_XChangeWindowAttributes) (
    Display*		/* display */,
    Window		/* w */,
    unsigned long	/* valuemask */,
    XSetWindowAttributes* /* attributes */
);
IVX11EXTERN Bool (*ivdynam_XCheckIfEvent) (
    Display*		/* display */,
    XEvent*		/* event_return */,
    Bool (*) (
	       Display*			/* display */,
               XEvent*			/* event */,
               XPointer			/* arg */
             )		/* predicate */,
    XPointer		/* arg */
);
IVX11EXTERN Bool (*ivdynam_XCheckMaskEvent) (
    Display*		/* display */,
    long		/* event_mask */,
    XEvent*		/* event_return */
);
IVX11EXTERN Bool (*ivdynam_XCheckTypedEvent) (
    Display*		/* display */,
    int			/* event_type */,
    XEvent*		/* event_return */
);
IVX11EXTERN Bool (*ivdynam_XCheckTypedWindowEvent) (
    Display*		/* display */,
    Window		/* w */,
    int			/* event_type */,
    XEvent*		/* event_return */
);
IVX11EXTERN Bool (*ivdynam_XCheckWindowEvent) (
    Display*		/* display */,
    Window		/* w */,
    long		/* event_mask */,
    XEvent*		/* event_return */
);
IVX11EXTERN int (*ivdynam_XCirculateSubwindows) (
    Display*		/* display */,
    Window		/* w */,
    int			/* direction */
);
IVX11EXTERN int (*ivdynam_XCirculateSubwindowsDown) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XCirculateSubwindowsUp) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XClearArea) (
    Display*		/* display */,
    Window		/* w */,
    int			/* x */,
    int			/* y */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    Bool		/* exposures */
);
IVX11EXTERN int (*ivdynam_XClearWindow) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XCloseDisplay) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XConfigureWindow) (
    Display*		/* display */,
    Window		/* w */,
    unsigned int	/* value_mask */,
    XWindowChanges*	/* values */
);
IVX11EXTERN int (*ivdynam_XConnectionNumber) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XConvertSelection) (
    Display*		/* display */,
    Atom		/* selection */,
    Atom 		/* target */,
    Atom		/* property */,
    Window		/* requestor */,
    Time		/* time */
);
IVX11EXTERN int (*ivdynam_XCopyArea) (
    Display*		/* display */,
    Drawable		/* src */,
    Drawable		/* dest */,
    GC			/* gc */,
    int			/* src_x */,
    int			/* src_y */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    int			/* dest_x */,
    int			/* dest_y */
);
IVX11EXTERN int (*ivdynam_XCopyGC) (
    Display*		/* display */,
    GC			/* src */,
    unsigned long	/* valuemask */,
    GC			/* dest */
);
IVX11EXTERN int (*ivdynam_XCopyPlane) (
    Display*		/* display */,
    Drawable		/* src */,
    Drawable		/* dest */,
    GC			/* gc */,
    int			/* src_x */,
    int			/* src_y */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    int			/* dest_x */,
    int			/* dest_y */,
    unsigned long	/* plane */
);
IVX11EXTERN int (*ivdynam_XDefaultDepth) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN int (*ivdynam_XDefaultDepthOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN int (*ivdynam_XDefaultScreen) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XDefineCursor) (
    Display*		/* display */,
    Window		/* w */,
    Cursor		/* cursor */
);
IVX11EXTERN int (*ivdynam_XDeleteProperty) (
    Display*		/* display */,
    Window		/* w */,
    Atom		/* property */
);
IVX11EXTERN int (*ivdynam_XDestroyWindow) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XDestroySubwindows) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XDoesBackingStore) (
    Screen*		/* screen */
);
IVX11EXTERN Bool (*ivdynam_XDoesSaveUnders) (
    Screen*		/* screen */
);
IVX11EXTERN int (*ivdynam_XDisableAccessControl) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XDisplayCells) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN int (*ivdynam_XDisplayHeight) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN int (*ivdynam_XDisplayHeightMM) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN int (*ivdynam_XDisplayKeycodes) (
    Display*		/* display */,
    int*		/* min_keycodes_return */,
    int*		/* max_keycodes_return */
);
IVX11EXTERN int (*ivdynam_XDisplayPlanes) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN int (*ivdynam_XDisplayWidth) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN int (*ivdynam_XDisplayWidthMM) (
    Display*		/* display */,
    int			/* screen_number */
);
IVX11EXTERN int (*ivdynam_XDrawArc) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    int			/* angle1 */,
    int			/* angle2 */
);
IVX11EXTERN int (*ivdynam_XDrawArcs) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    XArc*		/* arcs */,
    int			/* narcs */
);
IVX11EXTERN int (*ivdynam_XDrawImageString) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    _Xconst char*	/* string */,
    int			/* length */
);
IVX11EXTERN int (*ivdynam_XDrawImageString16) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    _Xconst XChar2b*	/* string */,
    int			/* length */
);
IVX11EXTERN int (*ivdynam_XDrawLine) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x1 */,
    int			/* y1 */,
    int			/* x2 */,
    int			/* y2 */
);
IVX11EXTERN int (*ivdynam_XDrawLines) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    XPoint*		/* points */,
    int			/* npoints */,
    int			/* mode */
);
IVX11EXTERN int (*ivdynam_XDrawPoint) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */
);
IVX11EXTERN int (*ivdynam_XDrawPoints) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    XPoint*		/* points */,
    int			/* npoints */,
    int			/* mode */
);
IVX11EXTERN int (*ivdynam_XDrawRectangle) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    unsigned int	/* width */,
    unsigned int	/* height */
);
IVX11EXTERN int (*ivdynam_XDrawRectangles) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    XRectangle*		/* rectangles */,
    int			/* nrectangles */
);
IVX11EXTERN int (*ivdynam_XDrawSegments) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    XSegment*		/* segments */,
    int			/* nsegments */
);
IVX11EXTERN int (*ivdynam_XDrawString) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    _Xconst char*	/* string */,
    int			/* length */
);
IVX11EXTERN int (*ivdynam_XDrawString16) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    _Xconst XChar2b*	/* string */,
    int			/* length */
);
IVX11EXTERN int (*ivdynam_XDrawText) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    XTextItem*		/* items */,
    int			/* nitems */
);
IVX11EXTERN int (*ivdynam_XDrawText16) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    XTextItem16*	/* items */,
    int			/* nitems */
);
IVX11EXTERN int (*ivdynam_XEnableAccessControl) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XEventsQueued) (
    Display*		/* display */,
    int			/* mode */
);
IVX11EXTERN Status (*ivdynam_XFetchName) (
    Display*		/* display */,
    Window		/* w */,
    char**		/* window_name_return */
);
IVX11EXTERN int (*ivdynam_XFillArc) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    int			/* angle1 */,
    int			/* angle2 */
);
IVX11EXTERN int (*ivdynam_XFillArcs) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    XArc*		/* arcs */,
    int			/* narcs */
);
IVX11EXTERN int (*ivdynam_XFillPolygon) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    XPoint*		/* points */,
    int			/* npoints */,
    int			/* shape */,
    int			/* mode */
);
IVX11EXTERN int (*ivdynam_XFillRectangle) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    unsigned int	/* width */,
    unsigned int	/* height */
);
IVX11EXTERN int (*ivdynam_XFillRectangles) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    XRectangle*		/* rectangles */,
    int			/* nrectangles */
);
IVX11EXTERN int (*ivdynam_XFlush) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XForceScreenSaver) (
    Display*		/* display */,
    int			/* mode */
);
IVX11EXTERN int (*ivdynam_XFree) (
    void*		/* data */
);
IVX11EXTERN int (*ivdynam_XFreeColormap) (
    Display*		/* display */,
    Colormap		/* colormap */
);
IVX11EXTERN int (*ivdynam_XFreeColors) (
    Display*		/* display */,
    Colormap		/* colormap */,
    unsigned long*	/* pixels */,
    int			/* npixels */,
    unsigned long	/* planes */
);
IVX11EXTERN int (*ivdynam_XFreeCursor) (
    Display*		/* display */,
    Cursor		/* cursor */
);
IVX11EXTERN int (*ivdynam_XFreeExtensionList) (
    char**		/* list */
);
IVX11EXTERN int (*ivdynam_XFreeFont) (
    Display*		/* display */,
    XFontStruct*	/* font_struct */
);
IVX11EXTERN int (*ivdynam_XFreeFontInfo) (
    char**		/* names */,
    XFontStruct*	/* free_info */,
    int			/* actual_count */
);
IVX11EXTERN int (*ivdynam_XFreeFontNames) (
    char**		/* list */
);
IVX11EXTERN int (*ivdynam_XFreeFontPath) (
    char**		/* list */
);
IVX11EXTERN int (*ivdynam_XFreeGC) (
    Display*		/* display */,
    GC			/* gc */
);
IVX11EXTERN int (*ivdynam_XFreeModifiermap) (
    XModifierKeymap*	/* modmap */
);
IVX11EXTERN int (*ivdynam_XFreePixmap) (
    Display*		/* display */,
    Pixmap		/* pixmap */
);
IVX11EXTERN int (*ivdynam_XGeometry) (
    Display*		/* display */,
    int			/* screen */,
    _Xconst char*	/* position */,
    _Xconst char*	/* default_position */,
    unsigned int	/* bwidth */,
    unsigned int	/* fwidth */,
    unsigned int	/* fheight */,
    int			/* xadder */,
    int			/* yadder */,
    int*		/* x_return */,
    int*		/* y_return */,
    int*		/* width_return */,
    int*		/* height_return */
);
IVX11EXTERN int (*ivdynam_XGetErrorDatabaseText) (
    Display*		/* display */,
    _Xconst char*	/* name */,
    _Xconst char*	/* message */,
    _Xconst char*	/* default_string */,
    char*		/* buffer_return */,
    int			/* length */
);
IVX11EXTERN int (*ivdynam_XGetErrorText) (
    Display*		/* display */,
    int			/* code */,
    char*		/* buffer_return */,
    int			/* length */
);
IVX11EXTERN Bool (*ivdynam_XGetFontProperty) (
    XFontStruct*	/* font_struct */,
    Atom		/* atom */,
    unsigned long*	/* value_return */
);
IVX11EXTERN Status (*ivdynam_XGetGCValues) (
    Display*		/* display */,
    GC			/* gc */,
    unsigned long	/* valuemask */,
    XGCValues*		/* values_return */
);
IVX11EXTERN Status (*ivdynam_XGetGeometry) (
    Display*		/* display */,
    Drawable		/* d */,
    Window*		/* root_return */,
    int*		/* x_return */,
    int*		/* y_return */,
    unsigned int*	/* width_return */,
    unsigned int*	/* height_return */,
    unsigned int*	/* border_width_return */,
    unsigned int*	/* depth_return */
);
IVX11EXTERN Status (*ivdynam_XGetIconName) (
    Display*		/* display */,
    Window		/* w */,
    char**		/* icon_name_return */
);
IVX11EXTERN int (*ivdynam_XGetInputFocus) (
    Display*		/* display */,
    Window*		/* focus_return */,
    int*		/* revert_to_return */
);
IVX11EXTERN int (*ivdynam_XGetKeyboardControl) (
    Display*		/* display */,
    XKeyboardState*	/* values_return */
);
IVX11EXTERN int (*ivdynam_XGetPointerControl) (
    Display*		/* display */,
    int*		/* accel_numerator_return */,
    int*		/* accel_denominator_return */,
    int*		/* threshold_return */
);
IVX11EXTERN int (*ivdynam_XGetPointerMapping) (
    Display*		/* display */,
    unsigned char*	/* map_return */,
    int			/* nmap */
);
IVX11EXTERN int (*ivdynam_XGetScreenSaver) (
    Display*		/* display */,
    int*		/* timeout_return */,
    int*		/* interval_return */,
    int*		/* prefer_blanking_return */,
    int*		/* allow_exposures_return */
);
IVX11EXTERN Status (*ivdynam_XGetTransientForHint) (
    Display*		/* display */,
    Window		/* w */,
    Window*		/* prop_window_return */
);
IVX11EXTERN int (*ivdynam_XGetWindowProperty) (
    Display*		/* display */,
    Window		/* w */,
    Atom		/* property */,
    long		/* long_offset */,
    long		/* long_length */,
    Bool		/* delete */,
    Atom		/* req_type */,
    Atom*		/* actual_type_return */,
    int*		/* actual_format_return */,
    unsigned long*	/* nitems_return */,
    unsigned long*	/* bytes_after_return */,
    unsigned char**	/* prop_return */
);
IVX11EXTERN Status (*ivdynam_XGetWindowAttributes) (
    Display*		/* display */,
    Window		/* w */,
    XWindowAttributes*	/* window_attributes_return */
);
IVX11EXTERN int (*ivdynam_XGrabButton) (
    Display*		/* display */,
    unsigned int	/* button */,
    unsigned int	/* modifiers */,
    Window		/* grab_window */,
    Bool		/* owner_events */,
    unsigned int	/* event_mask */,
    int			/* pointer_mode */,
    int			/* keyboard_mode */,
    Window		/* confine_to */,
    Cursor		/* cursor */
);
IVX11EXTERN int (*ivdynam_XGrabKey) (
    Display*		/* display */,
    int			/* keycode */,
    unsigned int	/* modifiers */,
    Window		/* grab_window */,
    Bool		/* owner_events */,
    int			/* pointer_mode */,
    int			/* keyboard_mode */
);
IVX11EXTERN int (*ivdynam_XGrabKeyboard) (
    Display*		/* display */,
    Window		/* grab_window */,
    Bool		/* owner_events */,
    int			/* pointer_mode */,
    int			/* keyboard_mode */,
    Time		/* time */
);
IVX11EXTERN int (*ivdynam_XGrabPointer) (
    Display*		/* display */,
    Window		/* grab_window */,
    Bool		/* owner_events */,
    unsigned int	/* event_mask */,
    int			/* pointer_mode */,
    int			/* keyboard_mode */,
    Window		/* confine_to */,
    Cursor		/* cursor */,
    Time		/* time */
);
IVX11EXTERN int (*ivdynam_XGrabServer) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XHeightMMOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN int (*ivdynam_XHeightOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN int (*ivdynam_XIfEvent) (
    Display*		/* display */,
    XEvent*		/* event_return */,
    Bool (*) (
	       Display*			/* display */,
               XEvent*			/* event */,
               XPointer			/* arg */
             )		/* predicate */,
    XPointer		/* arg */
);
IVX11EXTERN int (*ivdynam_XImageByteOrder) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XInstallColormap) (
    Display*		/* display */,
    Colormap		/* colormap */
);
IVX11EXTERN KeyCode (*ivdynam_XKeysymToKeycode) (
    Display*		/* display */,
    KeySym		/* keysym */
);
IVX11EXTERN int (*ivdynam_XKillClient) (
    Display*		/* display */,
    XID			/* resource */
);
IVX11EXTERN Status (*ivdynam_XLookupColor) (
    Display*		/* display */,
    Colormap		/* colormap */,
    _Xconst char*	/* color_name */,
    XColor*		/* exact_def_return */,
    XColor*		/* screen_def_return */
);
IVX11EXTERN int (*ivdynam_XLowerWindow) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XMapRaised) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XMapSubwindows) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XMapWindow) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XMaskEvent) (
    Display*		/* display */,
    long		/* event_mask */,
    XEvent*		/* event_return */
);
IVX11EXTERN int (*ivdynam_XMaxCmapsOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN int (*ivdynam_XMinCmapsOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN int (*ivdynam_XMoveResizeWindow) (
    Display*		/* display */,
    Window		/* w */,
    int			/* x */,
    int			/* y */,
    unsigned int	/* width */,
    unsigned int	/* height */
);
IVX11EXTERN int (*ivdynam_XMoveWindow) (
    Display*		/* display */,
    Window		/* w */,
    int			/* x */,
    int			/* y */
);
IVX11EXTERN int (*ivdynam_XNextEvent) (
    Display*		/* display */,
    XEvent*		/* event_return */
);
IVX11EXTERN int (*ivdynam_XNoOp) (
    Display*		/* display */
);
IVX11EXTERN Status (*ivdynam_XParseColor) (
    Display*		/* display */,
    Colormap		/* colormap */,
    _Xconst char*	/* spec */,
    XColor*		/* exact_def_return */
);
IVX11EXTERN int (*ivdynam_XParseGeometry) (
    _Xconst char*	/* parsestring */,
    int*		/* x_return */,
    int*		/* y_return */,
    unsigned int*	/* width_return */,
    unsigned int*	/* height_return */
);
IVX11EXTERN int (*ivdynam_XPeekEvent) (
    Display*		/* display */,
    XEvent*		/* event_return */
);
IVX11EXTERN int (*ivdynam_XPeekIfEvent) (
    Display*		/* display */,
    XEvent*		/* event_return */,
    Bool (*) (
	       Display*		/* display */,
               XEvent*		/* event */,
               XPointer		/* arg */
             )		/* predicate */,
    XPointer		/* arg */
);
IVX11EXTERN int (*ivdynam_XPending) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XPlanesOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN int (*ivdynam_XProtocolRevision) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XProtocolVersion) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XPutBackEvent) (
    Display*		/* display */,
    XEvent*		/* event */
);
IVX11EXTERN int (*ivdynam_XPutImage) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    XImage*		/* image */,
    int			/* src_x */,
    int			/* src_y */,
    int			/* dest_x */,
    int			/* dest_y */,
    unsigned int	/* width */,
    unsigned int	/* height */
);
IVX11EXTERN int (*ivdynam_XQLength) (
    Display*		/* display */
);
IVX11EXTERN Status (*ivdynam_XQueryBestCursor) (
    Display*		/* display */,
    Drawable		/* d */,
    unsigned int        /* width */,
    unsigned int	/* height */,
    unsigned int*	/* width_return */,
    unsigned int*	/* height_return */
);
IVX11EXTERN Status (*ivdynam_XQueryBestSize) (
    Display*		/* display */,
    int			/* class */,
    Drawable		/* which_screen */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    unsigned int*	/* width_return */,
    unsigned int*	/* height_return */
);
IVX11EXTERN Status (*ivdynam_XQueryBestStipple) (
    Display*		/* display */,
    Drawable		/* which_screen */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    unsigned int*	/* width_return */,
    unsigned int*	/* height_return */
);
IVX11EXTERN Status (*ivdynam_XQueryBestTile) (
    Display*		/* display */,
    Drawable		/* which_screen */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    unsigned int*	/* width_return */,
    unsigned int*	/* height_return */
);
IVX11EXTERN int (*ivdynam_XQueryColor) (
    Display*		/* display */,
    Colormap		/* colormap */,
    XColor*		/* def_in_out */
);
IVX11EXTERN int (*ivdynam_XQueryColors) (
    Display*		/* display */,
    Colormap		/* colormap */,
    XColor*		/* defs_in_out */,
    int			/* ncolors */
);
IVX11EXTERN Bool (*ivdynam_XQueryExtension) (
    Display*		/* display */,
    _Xconst char*	/* name */,
    int*		/* major_opcode_return */,
    int*		/* first_event_return */,
    int*		/* first_error_return */
);
IVX11EXTERN int (*ivdynam_XQueryKeymap) (
    Display*		/* display */,
    char [32]		/* keys_return */
);
IVX11EXTERN Bool (*ivdynam_XQueryPointer) (
    Display*		/* display */,
    Window		/* w */,
    Window*		/* root_return */,
    Window*		/* child_return */,
    int*		/* root_x_return */,
    int*		/* root_y_return */,
    int*		/* win_x_return */,
    int*		/* win_y_return */,
    unsigned int*       /* mask_return */
);
IVX11EXTERN int (*ivdynam_XQueryTextExtents) (
    Display*		/* display */,
    XID			/* font_ID */,
    _Xconst char*	/* string */,
    int			/* nchars */,
    int*		/* direction_return */,
    int*		/* font_ascent_return */,
    int*		/* font_descent_return */,
    XCharStruct*	/* overall_return */
);
IVX11EXTERN int (*ivdynam_XQueryTextExtents16) (
    Display*		/* display */,
    XID			/* font_ID */,
    _Xconst XChar2b*	/* string */,
    int			/* nchars */,
    int*		/* direction_return */,
    int*		/* font_ascent_return */,
    int*		/* font_descent_return */,
    XCharStruct*	/* overall_return */
);
IVX11EXTERN Status (*ivdynam_XQueryTree) (
    Display*		/* display */,
    Window		/* w */,
    Window*		/* root_return */,
    Window*		/* parent_return */,
    Window**		/* children_return */,
    unsigned int*	/* nchildren_return */
);
IVX11EXTERN int (*ivdynam_XRaiseWindow) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XReadBitmapFile) (
    Display*		/* display */,
    Drawable 		/* d */,
    _Xconst char*	/* filename */,
    unsigned int*	/* width_return */,
    unsigned int*	/* height_return */,
    Pixmap*		/* bitmap_return */,
    int*		/* x_hot_return */,
    int*		/* y_hot_return */
);
IVX11EXTERN int (*ivdynam_XReadBitmapFileData) (
    _Xconst char*	/* filename */,
    unsigned int*	/* width_return */,
    unsigned int*	/* height_return */,
    unsigned char**	/* data_return */,
    int*		/* x_hot_return */,
    int*		/* y_hot_return */
);
IVX11EXTERN int (*ivdynam_XRebindKeysym) (
    Display*		/* display */,
    KeySym		/* keysym */,
    KeySym*		/* list */,
    int			/* mod_count */,
    _Xconst unsigned char*	/* string */,
    int			/* bytes_string */
);
IVX11EXTERN int (*ivdynam_XRecolorCursor) (
    Display*		/* display */,
    Cursor		/* cursor */,
    XColor*		/* foreground_color */,
    XColor*		/* background_color */
);
IVX11EXTERN int (*ivdynam_XRefreshKeyboardMapping) (
    XMappingEvent*	/* event_map */
);
IVX11EXTERN int (*ivdynam_XRemoveFromSaveSet) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XRemoveHost) (
    Display*		/* display */,
    XHostAddress*	/* host */
);
IVX11EXTERN int (*ivdynam_XRemoveHosts) (
    Display*		/* display */,
    XHostAddress*	/* hosts */,
    int			/* num_hosts */
);
IVX11EXTERN int (*ivdynam_XReparentWindow) (
    Display*		/* display */,
    Window		/* w */,
    Window		/* parent */,
    int			/* x */,
    int			/* y */
);
IVX11EXTERN int (*ivdynam_XResetScreenSaver) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XResizeWindow) (
    Display*		/* display */,
    Window		/* w */,
    unsigned int	/* width */,
    unsigned int	/* height */
);
IVX11EXTERN int (*ivdynam_XRestackWindows) (
    Display*		/* display */,
    Window*		/* windows */,
    int			/* nwindows */
);
IVX11EXTERN int (*ivdynam_XRotateBuffers) (
    Display*		/* display */,
    int			/* rotate */
);
IVX11EXTERN int (*ivdynam_XRotateWindowProperties) (
    Display*		/* display */,
    Window		/* w */,
    Atom*		/* properties */,
    int			/* num_prop */,
    int			/* npositions */
);
IVX11EXTERN int (*ivdynam_XScreenCount) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XSelectInput) (
    Display*		/* display */,
    Window		/* w */,
    long		/* event_mask */
);
IVX11EXTERN Status (*ivdynam_XSendEvent) (
    Display*		/* display */,
    Window		/* w */,
    Bool		/* propagate */,
    long		/* event_mask */,
    XEvent*		/* event_send */
);
IVX11EXTERN int (*ivdynam_XSetAccessControl) (
    Display*		/* display */,
    int			/* mode */
);
IVX11EXTERN int (*ivdynam_XSetArcMode) (
    Display*		/* display */,
    GC			/* gc */,
    int			/* arc_mode */
);
IVX11EXTERN int (*ivdynam_XSetBackground) (
    Display*		/* display */,
    GC			/* gc */,
    unsigned long	/* background */
);
IVX11EXTERN int (*ivdynam_XSetClipMask) (
    Display*		/* display */,
    GC			/* gc */,
    Pixmap		/* pixmap */
);
IVX11EXTERN int (*ivdynam_XSetClipOrigin) (
    Display*		/* display */,
    GC			/* gc */,
    int			/* clip_x_origin */,
    int			/* clip_y_origin */
);
IVX11EXTERN int (*ivdynam_XSetClipRectangles) (
    Display*		/* display */,
    GC			/* gc */,
    int			/* clip_x_origin */,
    int			/* clip_y_origin */,
    XRectangle*		/* rectangles */,
    int			/* n */,
    int			/* ordering */
);
IVX11EXTERN int (*ivdynam_XSetCloseDownMode) (
    Display*		/* display */,
    int			/* close_mode */
);
IVX11EXTERN int (*ivdynam_XSetCommand) (
    Display*		/* display */,
    Window		/* w */,
    char**		/* argv */,
    int			/* argc */
);
IVX11EXTERN int (*ivdynam_XSetDashes) (
    Display*		/* display */,
    GC			/* gc */,
    int			/* dash_offset */,
    _Xconst char*	/* dash_list */,
    int			/* n */
);
IVX11EXTERN int (*ivdynam_XSetFillRule) (
    Display*		/* display */,
    GC			/* gc */,
    int			/* fill_rule */
);
IVX11EXTERN int (*ivdynam_XSetFillStyle) (
    Display*		/* display */,
    GC			/* gc */,
    int			/* fill_style */
);
IVX11EXTERN int (*ivdynam_XSetFont) (
    Display*		/* display */,
    GC			/* gc */,
    Font		/* font */
);
IVX11EXTERN int (*ivdynam_XSetFontPath) (
    Display*		/* display */,
    char**		/* directories */,
    int			/* ndirs */
);
IVX11EXTERN int (*ivdynam_XSetForeground) (
    Display*		/* display */,
    GC			/* gc */,
    unsigned long	/* foreground */
);
IVX11EXTERN int (*ivdynam_XSetFunction) (
    Display*		/* display */,
    GC			/* gc */,
    int			/* function */
);
IVX11EXTERN int (*ivdynam_XSetGraphicsExposures) (
    Display*		/* display */,
    GC			/* gc */,
    Bool		/* graphics_exposures */
);
IVX11EXTERN int (*ivdynam_XSetIconName) (
    Display*		/* display */,
    Window		/* w */,
    _Xconst char*	/* icon_name */
);
IVX11EXTERN int (*ivdynam_XSetInputFocus) (
    Display*		/* display */,
    Window		/* focus */,
    int			/* revert_to */,
    Time		/* time */
);
IVX11EXTERN int (*ivdynam_XSetLineAttributes) (
    Display*		/* display */,
    GC			/* gc */,
    unsigned int	/* line_width */,
    int			/* line_style */,
    int			/* cap_style */,
    int			/* join_style */
);
IVX11EXTERN int (*ivdynam_XSetModifierMapping) (
    Display*		/* display */,
    XModifierKeymap*	/* modmap */
);
IVX11EXTERN int (*ivdynam_XSetPlaneMask) (
    Display*		/* display */,
    GC			/* gc */,
    unsigned long	/* plane_mask */
);
IVX11EXTERN int (*ivdynam_XSetPointerMapping) (
    Display*		/* display */,
    _Xconst unsigned char*	/* map */,
    int			/* nmap */
);
IVX11EXTERN int (*ivdynam_XSetScreenSaver) (
    Display*		/* display */,
    int			/* timeout */,
    int			/* interval */,
    int			/* prefer_blanking */,
    int			/* allow_exposures */
);
IVX11EXTERN int (*ivdynam_XSetSelectionOwner) (
    Display*		/* display */,
    Atom	        /* selection */,
    Window		/* owner */,
    Time		/* time */
);
IVX11EXTERN int (*ivdynam_XSetState) (
    Display*		/* display */,
    GC			/* gc */,
    unsigned long 	/* foreground */,
    unsigned long	/* background */,
    int			/* function */,
    unsigned long	/* plane_mask */
);
IVX11EXTERN int (*ivdynam_XSetStipple) (
    Display*		/* display */,
    GC			/* gc */,
    Pixmap		/* stipple */
);
IVX11EXTERN int (*ivdynam_XSetSubwindowMode) (
    Display*		/* display */,
    GC			/* gc */,
    int			/* subwindow_mode */
);
IVX11EXTERN int (*ivdynam_XSetTSOrigin) (
    Display*		/* display */,
    GC			/* gc */,
    int			/* ts_x_origin */,
    int			/* ts_y_origin */
);
IVX11EXTERN int (*ivdynam_XSetTile) (
    Display*		/* display */,
    GC			/* gc */,
    Pixmap		/* tile */
);
IVX11EXTERN int (*ivdynam_XSetWindowBackground) (
    Display*		/* display */,
    Window		/* w */,
    unsigned long	/* background_pixel */
);
IVX11EXTERN int (*ivdynam_XSetWindowBackgroundPixmap) (
    Display*		/* display */,
    Window		/* w */,
    Pixmap		/* background_pixmap */
);
IVX11EXTERN int (*ivdynam_XSetWindowBorder) (
    Display*		/* display */,
    Window		/* w */,
    unsigned long	/* border_pixel */
);
IVX11EXTERN int (*ivdynam_XSetWindowBorderPixmap) (
    Display*		/* display */,
    Window		/* w */,
    Pixmap		/* border_pixmap */
);
IVX11EXTERN int (*ivdynam_XSetWindowBorderWidth) (
    Display*		/* display */,
    Window		/* w */,
    unsigned int	/* width */
);
IVX11EXTERN int (*ivdynam_XSetWindowColormap) (
    Display*		/* display */,
    Window		/* w */,
    Colormap		/* colormap */
);
IVX11EXTERN int (*ivdynam_XStoreBuffer) (
    Display*		/* display */,
    _Xconst char*	/* bytes */,
    int			/* nbytes */,
    int			/* buffer */
);
IVX11EXTERN int (*ivdynam_XStoreBytes) (
    Display*		/* display */,
    _Xconst char*	/* bytes */,
    int			/* nbytes */
);
IVX11EXTERN int (*ivdynam_XStoreColor) (
    Display*		/* display */,
    Colormap		/* colormap */,
    XColor*		/* color */
);
IVX11EXTERN int (*ivdynam_XStoreColors) (
    Display*		/* display */,
    Colormap		/* colormap */,
    XColor*		/* color */,
    int			/* ncolors */
);
IVX11EXTERN int (*ivdynam_XStoreName) (
    Display*		/* display */,
    Window		/* w */,
    _Xconst char*	/* window_name */
);
IVX11EXTERN int (*ivdynam_XStoreNamedColor) (
    Display*		/* display */,
    Colormap		/* colormap */,
    _Xconst char*	/* color */,
    unsigned long	/* pixel */,
    int			/* flags */
);
IVX11EXTERN int (*ivdynam_XSync) (
    Display*		/* display */,
    Bool		/* discard */
);
IVX11EXTERN int (*ivdynam_XTextExtents) (
    XFontStruct*	/* font_struct */,
    _Xconst char*	/* string */,
    int			/* nchars */,
    int*		/* direction_return */,
    int*		/* font_ascent_return */,
    int*		/* font_descent_return */,
    XCharStruct*	/* overall_return */
);
IVX11EXTERN int (*ivdynam_XTextExtents16) (
    XFontStruct*	/* font_struct */,
    _Xconst XChar2b*	/* string */,
    int			/* nchars */,
    int*		/* direction_return */,
    int*		/* font_ascent_return */,
    int*		/* font_descent_return */,
    XCharStruct*	/* overall_return */
);
IVX11EXTERN int (*ivdynam_XTextWidth) (
    XFontStruct*	/* font_struct */,
    _Xconst char*	/* string */,
    int			/* count */
);
IVX11EXTERN int (*ivdynam_XTextWidth16) (
    XFontStruct*	/* font_struct */,
    _Xconst XChar2b*	/* string */,
    int			/* count */
);
IVX11EXTERN Bool (*ivdynam_XTranslateCoordinates) (
    Display*		/* display */,
    Window		/* src_w */,
    Window		/* dest_w */,
    int			/* src_x */,
    int			/* src_y */,
    int*		/* dest_x_return */,
    int*		/* dest_y_return */,
    Window*		/* child_return */
);
IVX11EXTERN int (*ivdynam_XUndefineCursor) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XUngrabButton) (
    Display*		/* display */,
    unsigned int	/* button */,
    unsigned int	/* modifiers */,
    Window		/* grab_window */
);
IVX11EXTERN int (*ivdynam_XUngrabKey) (
    Display*		/* display */,
    int			/* keycode */,
    unsigned int	/* modifiers */,
    Window		/* grab_window */
);
IVX11EXTERN int (*ivdynam_XUngrabKeyboard) (
    Display*		/* display */,
    Time		/* time */
);
IVX11EXTERN int (*ivdynam_XUngrabPointer) (
    Display*		/* display */,
    Time		/* time */
);
IVX11EXTERN int (*ivdynam_XUngrabServer) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XUninstallColormap) (
    Display*		/* display */,
    Colormap		/* colormap */
);
IVX11EXTERN int (*ivdynam_XUnloadFont) (
    Display*		/* display */,
    Font		/* font */
);
IVX11EXTERN int (*ivdynam_XUnmapSubwindows) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XUnmapWindow) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN int (*ivdynam_XVendorRelease) (
    Display*		/* display */
);
IVX11EXTERN int (*ivdynam_XWarpPointer) (
    Display*		/* display */,
    Window		/* src_w */,
    Window		/* dest_w */,
    int			/* src_x */,
    int			/* src_y */,
    unsigned int	/* src_width */,
    unsigned int	/* src_height */,
    int			/* dest_x */,
    int			/* dest_y */
);
IVX11EXTERN int (*ivdynam_XWidthMMOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN int (*ivdynam_XWidthOfScreen) (
    Screen*		/* screen */
);
IVX11EXTERN int (*ivdynam_XWindowEvent) (
    Display*		/* display */,
    Window		/* w */,
    long		/* event_mask */,
    XEvent*		/* event_return */
);
IVX11EXTERN int (*ivdynam_XWriteBitmapFile) (
    Display*		/* display */,
    _Xconst char*	/* filename */,
    Pixmap		/* bitmap */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    int			/* x_hot */,
    int			/* y_hot */
);
IVX11EXTERN XOM (*ivdynam_XOpenOM) (
    Display*			/* display */,
    struct _XrmHashBucketRec*	/* rdb */,
    _Xconst char*		/* res_name */,
    _Xconst char*		/* res_class */
);
IVX11EXTERN Status (*ivdynam_XCloseOM) (
    XOM			/* om */
);
IVX11EXTERN char * (*ivdynam_XSetOMValues) (
    XOM			/* om */,
    ...
) _X_SENTINEL(0);
IVX11EXTERN char * (*ivdynam_XGetOMValues) (
    XOM			/* om */,
    ...
) _X_SENTINEL(0);
IVX11EXTERN Display * (*ivdynam_XDisplayOfOM) (
    XOM			/* om */
);
IVX11EXTERN char * (*ivdynam_XLocaleOfOM) (
    XOM			/* om */
);
IVX11EXTERN XOC (*ivdynam_XCreateOC) (
    XOM			/* om */,
    ...
) _X_SENTINEL(0);
IVX11EXTERN void (*ivdynam_XDestroyOC) (
    XOC			/* oc */
);
IVX11EXTERN XOM (*ivdynam_XOMOfOC) (
    XOC			/* oc */
);
IVX11EXTERN char * (*ivdynam_XSetOCValues) (
    XOC			/* oc */,
    ...
) _X_SENTINEL(0);
IVX11EXTERN char * (*ivdynam_XGetOCValues) (
    XOC			/* oc */,
    ...
) _X_SENTINEL(0);
IVX11EXTERN XFontSet (*ivdynam_XCreateFontSet) (
    Display*		/* display */,
    _Xconst char*	/* base_font_name_list */,
    char***		/* missing_charset_list */,
    int*		/* missing_charset_count */,
    char**		/* def_string */
);
IVX11EXTERN void (*ivdynam_XFreeFontSet) (
    Display*		/* display */,
    XFontSet		/* font_set */
);
IVX11EXTERN int (*ivdynam_XFontsOfFontSet) (
    XFontSet		/* font_set */,
    XFontStruct***	/* font_struct_list */,
    char***		/* font_name_list */
);
IVX11EXTERN char * (*ivdynam_XBaseFontNameListOfFontSet) (
    XFontSet		/* font_set */
);
IVX11EXTERN char * (*ivdynam_XLocaleOfFontSet) (
    XFontSet		/* font_set */
);
IVX11EXTERN Bool (*ivdynam_XContextDependentDrawing) (
    XFontSet		/* font_set */
);
IVX11EXTERN Bool (*ivdynam_XDirectionalDependentDrawing) (
    XFontSet		/* font_set */
);
IVX11EXTERN Bool (*ivdynam_XContextualDrawing) (
    XFontSet		/* font_set */
);
IVX11EXTERN XFontSetExtents * (*ivdynam_XExtentsOfFontSet) (
    XFontSet		/* font_set */
);
IVX11EXTERN int (*ivdynam_XmbTextEscapement) (
    XFontSet		/* font_set */,
    _Xconst char*	/* text */,
    int			/* bytes_text */
);
IVX11EXTERN int (*ivdynam_XwcTextEscapement) (
    XFontSet		/* font_set */,
    _Xconst wchar_t*	/* text */,
    int			/* num_wchars */
);
IVX11EXTERN int (*ivdynam_Xutf8TextEscapement) (
    XFontSet		/* font_set */,
    _Xconst char*	/* text */,
    int			/* bytes_text */
);
IVX11EXTERN int (*ivdynam_XmbTextExtents) (
    XFontSet		/* font_set */,
    _Xconst char*	/* text */,
    int			/* bytes_text */,
    XRectangle*		/* overall_ink_return */,
    XRectangle*		/* overall_logical_return */
);
IVX11EXTERN int (*ivdynam_XwcTextExtents) (
    XFontSet		/* font_set */,
    _Xconst wchar_t*	/* text */,
    int			/* num_wchars */,
    XRectangle*		/* overall_ink_return */,
    XRectangle*		/* overall_logical_return */
);
IVX11EXTERN int (*ivdynam_Xutf8TextExtents) (
    XFontSet		/* font_set */,
    _Xconst char*	/* text */,
    int			/* bytes_text */,
    XRectangle*		/* overall_ink_return */,
    XRectangle*		/* overall_logical_return */
);
IVX11EXTERN Status (*ivdynam_XmbTextPerCharExtents) (
    XFontSet		/* font_set */,
    _Xconst char*	/* text */,
    int			/* bytes_text */,
    XRectangle*		/* ink_extents_buffer */,
    XRectangle*		/* logical_extents_buffer */,
    int			/* buffer_size */,
    int*		/* num_chars */,
    XRectangle*		/* overall_ink_return */,
    XRectangle*		/* overall_logical_return */
);
IVX11EXTERN Status (*ivdynam_XwcTextPerCharExtents) (
    XFontSet		/* font_set */,
    _Xconst wchar_t*	/* text */,
    int			/* num_wchars */,
    XRectangle*		/* ink_extents_buffer */,
    XRectangle*		/* logical_extents_buffer */,
    int			/* buffer_size */,
    int*		/* num_chars */,
    XRectangle*		/* overall_ink_return */,
    XRectangle*		/* overall_logical_return */
);
IVX11EXTERN Status (*ivdynam_Xutf8TextPerCharExtents) (
    XFontSet		/* font_set */,
    _Xconst char*	/* text */,
    int			/* bytes_text */,
    XRectangle*		/* ink_extents_buffer */,
    XRectangle*		/* logical_extents_buffer */,
    int			/* buffer_size */,
    int*		/* num_chars */,
    XRectangle*		/* overall_ink_return */,
    XRectangle*		/* overall_logical_return */
);
IVX11EXTERN void (*ivdynam_XmbDrawText) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    XmbTextItem*	/* text_items */,
    int			/* nitems */
);
IVX11EXTERN void (*ivdynam_XwcDrawText) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    XwcTextItem*	/* text_items */,
    int			/* nitems */
);
IVX11EXTERN void (*ivdynam_Xutf8DrawText) (
    Display*		/* display */,
    Drawable		/* d */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    XmbTextItem*	/* text_items */,
    int			/* nitems */
);
IVX11EXTERN void (*ivdynam_XmbDrawString) (
    Display*		/* display */,
    Drawable		/* d */,
    XFontSet		/* font_set */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    _Xconst char*	/* text */,
    int			/* bytes_text */
);
IVX11EXTERN void (*ivdynam_XwcDrawString) (
    Display*		/* display */,
    Drawable		/* d */,
    XFontSet		/* font_set */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    _Xconst wchar_t*	/* text */,
    int			/* num_wchars */
);
IVX11EXTERN void (*ivdynam_Xutf8DrawString) (
    Display*		/* display */,
    Drawable		/* d */,
    XFontSet		/* font_set */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    _Xconst char*	/* text */,
    int			/* bytes_text */
);
IVX11EXTERN void (*ivdynam_XmbDrawImageString) (
    Display*		/* display */,
    Drawable		/* d */,
    XFontSet		/* font_set */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    _Xconst char*	/* text */,
    int			/* bytes_text */
);
IVX11EXTERN void (*ivdynam_XwcDrawImageString) (
    Display*		/* display */,
    Drawable		/* d */,
    XFontSet		/* font_set */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    _Xconst wchar_t*	/* text */,
    int			/* num_wchars */
);
IVX11EXTERN void (*ivdynam_Xutf8DrawImageString) (
    Display*		/* display */,
    Drawable		/* d */,
    XFontSet		/* font_set */,
    GC			/* gc */,
    int			/* x */,
    int			/* y */,
    _Xconst char*	/* text */,
    int			/* bytes_text */
);
IVX11EXTERN XIM (*ivdynam_XOpenIM) (
    Display*			/* dpy */,
    struct _XrmHashBucketRec*	/* rdb */,
    char*			/* res_name */,
    char*			/* res_class */
);
IVX11EXTERN Status (*ivdynam_XCloseIM) (
    XIM /* im */
);
IVX11EXTERN char * (*ivdynam_XGetIMValues) (
    XIM /* im */, ...
) _X_SENTINEL(0);
IVX11EXTERN char * (*ivdynam_XSetIMValues) (
    XIM /* im */, ...
) _X_SENTINEL(0);
IVX11EXTERN Display * (*ivdynam_XDisplayOfIM) (
    XIM /* im */
);
IVX11EXTERN char * (*ivdynam_XLocaleOfIM) (
    XIM /* im*/
);
IVX11EXTERN XIC (*ivdynam_XCreateIC) (
    XIM /* im */, ...
) _X_SENTINEL(0);
IVX11EXTERN void (*ivdynam_XDestroyIC) (
    XIC /* ic */
);
IVX11EXTERN void (*ivdynam_XSetICFocus) (
    XIC /* ic */
);
IVX11EXTERN void (*ivdynam_XUnsetICFocus) (
    XIC /* ic */
);
IVX11EXTERN wchar_t * (*ivdynam_XwcResetIC) (
    XIC /* ic */
);
IVX11EXTERN char * (*ivdynam_XmbResetIC) (
    XIC /* ic */
);
IVX11EXTERN char * (*ivdynam_Xutf8ResetIC) (
    XIC /* ic */
);
IVX11EXTERN char * (*ivdynam_XSetICValues) (
    XIC /* ic */, ...
) _X_SENTINEL(0);
IVX11EXTERN char * (*ivdynam_XGetICValues) (
    XIC /* ic */, ...
) _X_SENTINEL(0);
IVX11EXTERN XIM (*ivdynam_XIMOfIC) (
    XIC /* ic */
);
IVX11EXTERN Bool (*ivdynam_XFilterEvent) (
    XEvent*	/* event */,
    Window	/* window */
);
IVX11EXTERN int (*ivdynam_XmbLookupString) (
    XIC			/* ic */,
    XKeyPressedEvent*	/* event */,
    char*		/* buffer_return */,
    int			/* bytes_buffer */,
    KeySym*		/* keysym_return */,
    Status*		/* status_return */
);
IVX11EXTERN int (*ivdynam_XwcLookupString) (
    XIC			/* ic */,
    XKeyPressedEvent*	/* event */,
    wchar_t*		/* buffer_return */,
    int			/* wchars_buffer */,
    KeySym*		/* keysym_return */,
    Status*		/* status_return */
);
IVX11EXTERN int (*ivdynam_Xutf8LookupString) (
    XIC			/* ic */,
    XKeyPressedEvent*	/* event */,
    char*		/* buffer_return */,
    int			/* bytes_buffer */,
    KeySym*		/* keysym_return */,
    Status*		/* status_return */
);
IVX11EXTERN XVaNestedList (*ivdynam_XVaCreateNestedList) (
    int /*unused*/, ...
) _X_SENTINEL(0);
IVX11EXTERN Bool (*ivdynam_XRegisterIMInstantiateCallback) (
    Display*			/* dpy */,
    struct _XrmHashBucketRec*	/* rdb */,
    char*			/* res_name */,
    char*			/* res_class */,
    XIDProc			/* callback */,
    XPointer			/* client_data */
);
IVX11EXTERN Bool (*ivdynam_XUnregisterIMInstantiateCallback) (
    Display*			/* dpy */,
    struct _XrmHashBucketRec*	/* rdb */,
    char*			/* res_name */,
    char*			/* res_class */,
    XIDProc			/* callback */,
    XPointer			/* client_data */
);
IVX11EXTERN Status (*ivdynam_XInternalConnectionNumbers) (
    Display*			/* dpy */,
    int**			/* fd_return */,
    int*			/* count_return */
);
IVX11EXTERN void (*ivdynam_XProcessInternalConnection) (
    Display*			/* dpy */,
    int				/* fd */
);
IVX11EXTERN Status (*ivdynam_XAddConnectionWatch) (
    Display*			/* dpy */,
    XConnectionWatchProc	/* callback */,
    XPointer			/* client_data */
);
IVX11EXTERN void (*ivdynam_XRemoveConnectionWatch) (
    Display*			/* dpy */,
    XConnectionWatchProc	/* callback */,
    XPointer			/* client_data */
);
IVX11EXTERN void (*ivdynam_XSetAuthorization) (
    char *			/* name */,
    int				/* namelen */,
    char *			/* data */,
    int				/* datalen */
);
IVX11EXTERN int (*ivdynam__Xmbtowc) (
    wchar_t *			/* wstr */,
    char *			/* str */,
    int				/* len */
);
IVX11EXTERN int (*ivdynam__Xwctomb) (
    char *			/* str */,
    wchar_t			/* wc */
);
IVX11EXTERN int (*ivdynam_XDestroyImage) (
        XImage *ximage);
IVX11EXTERN unsigned long (*ivdynam_XGetPixel) (
        XImage *ximage,
        int x, int y);
IVX11EXTERN int (*ivdynam_XPutPixel) (
        XImage *ximage,
        int x, int y,
        unsigned long pixel);
IVX11EXTERN XImage * (*ivdynam_XSubImage) (
        XImage *ximage,
        int x, int y,
        unsigned int width, unsigned int height);
IVX11EXTERN int (*ivdynam_XAddPixel) (
        XImage *ximage,
        long value);
IVX11EXTERN XClassHint * (*ivdynam_XAllocClassHint) (
    void
);
IVX11EXTERN XIconSize * (*ivdynam_XAllocIconSize) (
    void
);
IVX11EXTERN XSizeHints * (*ivdynam_XAllocSizeHints) (
    void
);
IVX11EXTERN XStandardColormap * (*ivdynam_XAllocStandardColormap) (
    void
);
IVX11EXTERN XWMHints * (*ivdynam_XAllocWMHints) (
    void
);
IVX11EXTERN int (*ivdynam_XClipBox) (
    Region		/* r */,
    XRectangle*		/* rect_return */
);
IVX11EXTERN Region (*ivdynam_XCreateRegion) (
    void
);
IVX11EXTERN int (*ivdynam_XDestroyRegion) (
    Region		/* r */
);
IVX11EXTERN int (*ivdynam_XEmptyRegion) (
    Region		/* r */
);
IVX11EXTERN int (*ivdynam_XEqualRegion) (
    Region		/* r1 */,
    Region		/* r2 */
);
IVX11EXTERN int (*ivdynam_XFindContext) (
    Display*		/* display */,
    XID			/* rid */,
    XContext		/* context */,
    XPointer*		/* data_return */
);
IVX11EXTERN Status (*ivdynam_XGetClassHint) (
    Display*		/* display */,
    Window		/* w */,
    XClassHint*		/* class_hints_return */
);
IVX11EXTERN Status (*ivdynam_XGetIconSizes) (
    Display*		/* display */,
    Window		/* w */,
    XIconSize**		/* size_list_return */,
    int*		/* count_return */
);
IVX11EXTERN Status (*ivdynam_XGetNormalHints) (
    Display*		/* display */,
    Window		/* w */,
    XSizeHints*		/* hints_return */
);
IVX11EXTERN Status (*ivdynam_XGetRGBColormaps) (
    Display*		/* display */,
    Window		/* w */,
    XStandardColormap** /* stdcmap_return */,
    int*		/* count_return */,
    Atom		/* property */
);
IVX11EXTERN Status (*ivdynam_XGetSizeHints) (
    Display*		/* display */,
    Window		/* w */,
    XSizeHints*		/* hints_return */,
    Atom		/* property */
);
IVX11EXTERN Status (*ivdynam_XGetStandardColormap) (
    Display*		/* display */,
    Window		/* w */,
    XStandardColormap*	/* colormap_return */,
    Atom		/* property */
);
IVX11EXTERN Status (*ivdynam_XGetTextProperty) (
    Display*		/* display */,
    Window		/* window */,
    XTextProperty*	/* text_prop_return */,
    Atom		/* property */
);
IVX11EXTERN XVisualInfo * (*ivdynam_XGetVisualInfo) (
    Display*		/* display */,
    long		/* vinfo_mask */,
    XVisualInfo*	/* vinfo_template */,
    int*		/* nitems_return */
);
IVX11EXTERN Status (*ivdynam_XGetWMClientMachine) (
    Display*		/* display */,
    Window		/* w */,
    XTextProperty*	/* text_prop_return */
);
IVX11EXTERN XWMHints * (*ivdynam_XGetWMHints) (
    Display*		/* display */,
    Window		/* w */
);
IVX11EXTERN Status (*ivdynam_XGetWMIconName) (
    Display*		/* display */,
    Window		/* w */,
    XTextProperty*	/* text_prop_return */
);
IVX11EXTERN Status (*ivdynam_XGetWMName) (
    Display*		/* display */,
    Window		/* w */,
    XTextProperty*	/* text_prop_return */
);
IVX11EXTERN Status (*ivdynam_XGetWMNormalHints) (
    Display*		/* display */,
    Window		/* w */,
    XSizeHints*		/* hints_return */,
    long*		/* supplied_return */
);
IVX11EXTERN Status (*ivdynam_XGetWMSizeHints) (
    Display*		/* display */,
    Window		/* w */,
    XSizeHints*		/* hints_return */,
    long*		/* supplied_return */,
    Atom		/* property */
);
IVX11EXTERN Status (*ivdynam_XGetZoomHints) (
    Display*		/* display */,
    Window		/* w */,
    XSizeHints*		/* zhints_return */
);
IVX11EXTERN int (*ivdynam_XIntersectRegion) (
    Region		/* sra */,
    Region		/* srb */,
    Region		/* dr_return */
);
IVX11EXTERN void (*ivdynam_XConvertCase) (
    KeySym		/* sym */,
    KeySym*		/* lower */,
    KeySym*		/* upper */
);
IVX11EXTERN int (*ivdynam_XLookupString) (
    XKeyEvent*		/* event_struct */,
    char*		/* buffer_return */,
    int			/* bytes_buffer */,
    KeySym*		/* keysym_return */,
    XComposeStatus*	/* status_in_out */
);
IVX11EXTERN Status (*ivdynam_XMatchVisualInfo) (
    Display*		/* display */,
    int			/* screen */,
    int			/* depth */,
    int			/* class */,
    XVisualInfo*	/* vinfo_return */
);
IVX11EXTERN int (*ivdynam_XOffsetRegion) (
    Region		/* r */,
    int			/* dx */,
    int			/* dy */
);
IVX11EXTERN Bool (*ivdynam_XPointInRegion) (
    Region		/* r */,
    int			/* x */,
    int			/* y */
);
IVX11EXTERN Region (*ivdynam_XPolygonRegion) (
    XPoint*		/* points */,
    int			/* n */,
    int			/* fill_rule */
);
IVX11EXTERN int (*ivdynam_XRectInRegion) (
    Region		/* r */,
    int			/* x */,
    int			/* y */,
    unsigned int	/* width */,
    unsigned int	/* height */
);
IVX11EXTERN int (*ivdynam_XSaveContext) (
    Display*		/* display */,
    XID			/* rid */,
    XContext		/* context */,
    _Xconst char*	/* data */
);
IVX11EXTERN int (*ivdynam_XSetClassHint) (
    Display*		/* display */,
    Window		/* w */,
    XClassHint*		/* class_hints */
);
IVX11EXTERN int (*ivdynam_XSetIconSizes) (
    Display*		/* display */,
    Window		/* w */,
    XIconSize*		/* size_list */,
    int			/* count */
);
IVX11EXTERN int (*ivdynam_XSetNormalHints) (
    Display*		/* display */,
    Window		/* w */,
    XSizeHints*		/* hints */
);
IVX11EXTERN void (*ivdynam_XSetRGBColormaps) (
    Display*		/* display */,
    Window		/* w */,
    XStandardColormap*	/* stdcmaps */,
    int			/* count */,
    Atom		/* property */
);
IVX11EXTERN int (*ivdynam_XSetSizeHints) (
    Display*		/* display */,
    Window		/* w */,
    XSizeHints*		/* hints */,
    Atom		/* property */
);
IVX11EXTERN int (*ivdynam_XSetStandardProperties) (
    Display*		/* display */,
    Window		/* w */,
    _Xconst char*	/* window_name */,
    _Xconst char*	/* icon_name */,
    Pixmap		/* icon_pixmap */,
    char**		/* argv */,
    int			/* argc */,
    XSizeHints*		/* hints */
);
IVX11EXTERN void (*ivdynam_XSetTextProperty) (
    Display*		/* display */,
    Window		/* w */,
    XTextProperty*	/* text_prop */,
    Atom		/* property */
);
IVX11EXTERN void (*ivdynam_XSetWMClientMachine) (
    Display*		/* display */,
    Window		/* w */,
    XTextProperty*	/* text_prop */
);
IVX11EXTERN int (*ivdynam_XSetWMHints) (
    Display*		/* display */,
    Window		/* w */,
    XWMHints*		/* wm_hints */
);
IVX11EXTERN void (*ivdynam_XSetWMIconName) (
    Display*		/* display */,
    Window		/* w */,
    XTextProperty*	/* text_prop */
);
IVX11EXTERN void (*ivdynam_XSetWMName) (
    Display*		/* display */,
    Window		/* w */,
    XTextProperty*	/* text_prop */
);
IVX11EXTERN void (*ivdynam_XSetWMNormalHints) (
    Display*		/* display */,
    Window		/* w */,
    XSizeHints*		/* hints */
);
IVX11EXTERN void (*ivdynam_XSetWMProperties) (
    Display*		/* display */,
    Window		/* w */,
    XTextProperty*	/* window_name */,
    XTextProperty*	/* icon_name */,
    char**		/* argv */,
    int			/* argc */,
    XSizeHints*		/* normal_hints */,
    XWMHints*		/* wm_hints */,
    XClassHint*		/* class_hints */
);
IVX11EXTERN void (*ivdynam_XmbSetWMProperties) (
    Display*		/* display */,
    Window		/* w */,
    _Xconst char*	/* window_name */,
    _Xconst char*	/* icon_name */,
    char**		/* argv */,
    int			/* argc */,
    XSizeHints*		/* normal_hints */,
    XWMHints*		/* wm_hints */,
    XClassHint*		/* class_hints */
);
IVX11EXTERN void (*ivdynam_Xutf8SetWMProperties) (
    Display*		/* display */,
    Window		/* w */,
    _Xconst char*	/* window_name */,
    _Xconst char*	/* icon_name */,
    char**		/* argv */,
    int			/* argc */,
    XSizeHints*		/* normal_hints */,
    XWMHints*		/* wm_hints */,
    XClassHint*		/* class_hints */
);
IVX11EXTERN void (*ivdynam_XSetWMSizeHints) (
    Display*		/* display */,
    Window		/* w */,
    XSizeHints*		/* hints */,
    Atom		/* property */
);
IVX11EXTERN int (*ivdynam_XSetRegion) (
    Display*		/* display */,
    GC			/* gc */,
    Region		/* r */
);
IVX11EXTERN void (*ivdynam_XSetStandardColormap) (
    Display*		/* display */,
    Window		/* w */,
    XStandardColormap*	/* colormap */,
    Atom		/* property */
);
IVX11EXTERN int (*ivdynam_XSetZoomHints) (
    Display*		/* display */,
    Window		/* w */,
    XSizeHints*		/* zhints */
);
IVX11EXTERN int (*ivdynam_XShrinkRegion) (
    Region		/* r */,
    int			/* dx */,
    int			/* dy */
);
IVX11EXTERN Status (*ivdynam_XStringListToTextProperty) (
    char**		/* list */,
    int			/* count */,
    XTextProperty*	/* text_prop_return */
);
IVX11EXTERN int (*ivdynam_XSubtractRegion) (
    Region		/* sra */,
    Region		/* srb */,
    Region		/* dr_return */
);
IVX11EXTERN int (*ivdynam_XmbTextListToTextProperty) (
    Display*		display,
    char**		list,
    int			count,
    XICCEncodingStyle	style,
    XTextProperty*	text_prop_return
);
IVX11EXTERN int (*ivdynam_XwcTextListToTextProperty) (
    Display*		display,
    wchar_t**		list,
    int			count,
    XICCEncodingStyle	style,
    XTextProperty*	text_prop_return
);
IVX11EXTERN int (*ivdynam_Xutf8TextListToTextProperty) (
    Display*		display,
    char**		list,
    int			count,
    XICCEncodingStyle	style,
    XTextProperty*	text_prop_return
);
IVX11EXTERN void (*ivdynam_XwcFreeStringList) (
    wchar_t**		list
);
IVX11EXTERN Status (*ivdynam_XTextPropertyToStringList) (
    XTextProperty*	/* text_prop */,
    char***		/* list_return */,
    int*		/* count_return */
);
IVX11EXTERN int (*ivdynam_XmbTextPropertyToTextList) (
    Display*		display,
    const XTextProperty* text_prop,
    char***		list_return,
    int*		count_return
);
IVX11EXTERN int (*ivdynam_XwcTextPropertyToTextList) (
    Display*		display,
    const XTextProperty* text_prop,
    wchar_t***		list_return,
    int*		count_return
);
IVX11EXTERN int (*ivdynam_Xutf8TextPropertyToTextList) (
    Display*		display,
    const XTextProperty* text_prop,
    char***		list_return,
    int*		count_return
);
IVX11EXTERN int (*ivdynam_XUnionRectWithRegion) (
    XRectangle*		/* rectangle */,
    Region		/* src_region */,
    Region		/* dest_region_return */
);
IVX11EXTERN int (*ivdynam_XUnionRegion) (
    Region		/* sra */,
    Region		/* srb */,
    Region		/* dr_return */
);
IVX11EXTERN int (*ivdynam_XWMGeometry) (
    Display*		/* display */,
    int			/* screen_number */,
    _Xconst char*	/* user_geometry */,
    _Xconst char*	/* default_geometry */,
    unsigned int	/* border_width */,
    XSizeHints*		/* hints */,
    int*		/* x_return */,
    int*		/* y_return */,
    int*		/* width_return */,
    int*		/* height_return */,
    int*		/* gravity_return */
);
IVX11EXTERN int (*ivdynam_XXorRegion) (
    Region		/* sra */,
    Region		/* srb */,
    Region		/* dr_return */
);

#endif
