
/* automatically generated by mkdynam.py */
#ifndef ivx11_redef_h
#define ivx11_redef_h

#undef _Xdebug
#define _Xdebug (*ivdynam__Xdebug)
#undef XLoadQueryFont
#define XLoadQueryFont (*ivdynam_XLoadQueryFont)
#undef XQueryFont
#define XQueryFont (*ivdynam_XQueryFont)
#undef XGetMotionEvents
#define XGetMotionEvents (*ivdynam_XGetMotionEvents)
#undef XDeleteModifiermapEntry
#define XDeleteModifiermapEntry (*ivdynam_XDeleteModifiermapEntry)
#undef XGetModifierMapping
#define XGetModifierMapping (*ivdynam_XGetModifierMapping)
#undef XInsertModifiermapEntry
#define XInsertModifiermapEntry (*ivdynam_XInsertModifiermapEntry)
#undef XNewModifiermap
#define XNewModifiermap (*ivdynam_XNewModifiermap)
#undef XCreateImage
#define XCreateImage (*ivdynam_XCreateImage)
#undef XInitImage
#define XInitImage (*ivdynam_XInitImage)
#undef XGetImage
#define XGetImage (*ivdynam_XGetImage)
#undef XGetSubImage
#define XGetSubImage (*ivdynam_XGetSubImage)
#undef XOpenDisplay
#define XOpenDisplay (*ivdynam_XOpenDisplay)
#undef XrmInitialize
#define XrmInitialize (*ivdynam_XrmInitialize)
#undef XFetchBytes
#define XFetchBytes (*ivdynam_XFetchBytes)
#undef XFetchBuffer
#define XFetchBuffer (*ivdynam_XFetchBuffer)
#undef XGetAtomName
#define XGetAtomName (*ivdynam_XGetAtomName)
#undef XGetAtomNames
#define XGetAtomNames (*ivdynam_XGetAtomNames)
#undef XGetDefault
#define XGetDefault (*ivdynam_XGetDefault)
#undef XDisplayName
#define XDisplayName (*ivdynam_XDisplayName)
#undef XKeysymToString
#define XKeysymToString (*ivdynam_XKeysymToString)
#undef XSynchronize
#define XSynchronize (*ivdynam_XSynchronize)
#undef XSetAfterFunction
#define XSetAfterFunction (*ivdynam_XSetAfterFunction)
#undef XInternAtom
#define XInternAtom (*ivdynam_XInternAtom)
#undef XInternAtoms
#define XInternAtoms (*ivdynam_XInternAtoms)
#undef XCopyColormapAndFree
#define XCopyColormapAndFree (*ivdynam_XCopyColormapAndFree)
#undef XCreateColormap
#define XCreateColormap (*ivdynam_XCreateColormap)
#undef XCreatePixmapCursor
#define XCreatePixmapCursor (*ivdynam_XCreatePixmapCursor)
#undef XCreateGlyphCursor
#define XCreateGlyphCursor (*ivdynam_XCreateGlyphCursor)
#undef XCreateFontCursor
#define XCreateFontCursor (*ivdynam_XCreateFontCursor)
#undef XLoadFont
#define XLoadFont (*ivdynam_XLoadFont)
#undef XCreateGC
#define XCreateGC (*ivdynam_XCreateGC)
#undef XGContextFromGC
#define XGContextFromGC (*ivdynam_XGContextFromGC)
#undef XFlushGC
#define XFlushGC (*ivdynam_XFlushGC)
#undef XCreatePixmap
#define XCreatePixmap (*ivdynam_XCreatePixmap)
#undef XCreateBitmapFromData
#define XCreateBitmapFromData (*ivdynam_XCreateBitmapFromData)
#undef XCreatePixmapFromBitmapData
#define XCreatePixmapFromBitmapData (*ivdynam_XCreatePixmapFromBitmapData)
#undef XCreateSimpleWindow
#define XCreateSimpleWindow (*ivdynam_XCreateSimpleWindow)
#undef XGetSelectionOwner
#define XGetSelectionOwner (*ivdynam_XGetSelectionOwner)
#undef XCreateWindow
#define XCreateWindow (*ivdynam_XCreateWindow)
#undef XListInstalledColormaps
#define XListInstalledColormaps (*ivdynam_XListInstalledColormaps)
#undef XListFonts
#define XListFonts (*ivdynam_XListFonts)
#undef XListFontsWithInfo
#define XListFontsWithInfo (*ivdynam_XListFontsWithInfo)
#undef XGetFontPath
#define XGetFontPath (*ivdynam_XGetFontPath)
#undef XListExtensions
#define XListExtensions (*ivdynam_XListExtensions)
#undef XListProperties
#define XListProperties (*ivdynam_XListProperties)
#undef XListHosts
#define XListHosts (*ivdynam_XListHosts)
#undef XLookupKeysym
#define XLookupKeysym (*ivdynam_XLookupKeysym)
#undef XGetKeyboardMapping
#define XGetKeyboardMapping (*ivdynam_XGetKeyboardMapping)
#undef XStringToKeysym
#define XStringToKeysym (*ivdynam_XStringToKeysym)
#undef XMaxRequestSize
#define XMaxRequestSize (*ivdynam_XMaxRequestSize)
#undef XExtendedMaxRequestSize
#define XExtendedMaxRequestSize (*ivdynam_XExtendedMaxRequestSize)
#undef XResourceManagerString
#define XResourceManagerString (*ivdynam_XResourceManagerString)
#undef XScreenResourceString
#define XScreenResourceString (*ivdynam_XScreenResourceString)
#undef XDisplayMotionBufferSize
#define XDisplayMotionBufferSize (*ivdynam_XDisplayMotionBufferSize)
#undef XVisualIDFromVisual
#define XVisualIDFromVisual (*ivdynam_XVisualIDFromVisual)
#undef XInitThreads
#define XInitThreads (*ivdynam_XInitThreads)
#undef XLockDisplay
#define XLockDisplay (*ivdynam_XLockDisplay)
#undef XUnlockDisplay
#define XUnlockDisplay (*ivdynam_XUnlockDisplay)
#undef XInitExtension
#define XInitExtension (*ivdynam_XInitExtension)
#undef XAddExtension
#define XAddExtension (*ivdynam_XAddExtension)
#undef XFindOnExtensionList
#define XFindOnExtensionList (*ivdynam_XFindOnExtensionList)
#undef XEHeadOfExtensionList
#define XEHeadOfExtensionList (*ivdynam_XEHeadOfExtensionList)
#undef XRootWindow
#define XRootWindow (*ivdynam_XRootWindow)
#undef XDefaultRootWindow
#define XDefaultRootWindow (*ivdynam_XDefaultRootWindow)
#undef XRootWindowOfScreen
#define XRootWindowOfScreen (*ivdynam_XRootWindowOfScreen)
#undef XDefaultVisual
#define XDefaultVisual (*ivdynam_XDefaultVisual)
#undef XDefaultVisualOfScreen
#define XDefaultVisualOfScreen (*ivdynam_XDefaultVisualOfScreen)
#undef XDefaultGC
#define XDefaultGC (*ivdynam_XDefaultGC)
#undef XDefaultGCOfScreen
#define XDefaultGCOfScreen (*ivdynam_XDefaultGCOfScreen)
#undef XBlackPixel
#define XBlackPixel (*ivdynam_XBlackPixel)
#undef XWhitePixel
#define XWhitePixel (*ivdynam_XWhitePixel)
#undef XAllPlanes
#define XAllPlanes (*ivdynam_XAllPlanes)
#undef XBlackPixelOfScreen
#define XBlackPixelOfScreen (*ivdynam_XBlackPixelOfScreen)
#undef XWhitePixelOfScreen
#define XWhitePixelOfScreen (*ivdynam_XWhitePixelOfScreen)
#undef XNextRequest
#define XNextRequest (*ivdynam_XNextRequest)
#undef XLastKnownRequestProcessed
#define XLastKnownRequestProcessed (*ivdynam_XLastKnownRequestProcessed)
#undef XServerVendor
#define XServerVendor (*ivdynam_XServerVendor)
#undef XDisplayString
#define XDisplayString (*ivdynam_XDisplayString)
#undef XDefaultColormap
#define XDefaultColormap (*ivdynam_XDefaultColormap)
#undef XDefaultColormapOfScreen
#define XDefaultColormapOfScreen (*ivdynam_XDefaultColormapOfScreen)
#undef XDisplayOfScreen
#define XDisplayOfScreen (*ivdynam_XDisplayOfScreen)
#undef XScreenOfDisplay
#define XScreenOfDisplay (*ivdynam_XScreenOfDisplay)
#undef XDefaultScreenOfDisplay
#define XDefaultScreenOfDisplay (*ivdynam_XDefaultScreenOfDisplay)
#undef XEventMaskOfScreen
#define XEventMaskOfScreen (*ivdynam_XEventMaskOfScreen)
#undef XScreenNumberOfScreen
#define XScreenNumberOfScreen (*ivdynam_XScreenNumberOfScreen)
#undef XSetErrorHandler
#define XSetErrorHandler (*ivdynam_XSetErrorHandler)
#undef XSetIOErrorHandler
#define XSetIOErrorHandler (*ivdynam_XSetIOErrorHandler)
#undef XListPixmapFormats
#define XListPixmapFormats (*ivdynam_XListPixmapFormats)
#undef XListDepths
#define XListDepths (*ivdynam_XListDepths)
#undef XReconfigureWMWindow
#define XReconfigureWMWindow (*ivdynam_XReconfigureWMWindow)
#undef XGetWMProtocols
#define XGetWMProtocols (*ivdynam_XGetWMProtocols)
#undef XSetWMProtocols
#define XSetWMProtocols (*ivdynam_XSetWMProtocols)
#undef XIconifyWindow
#define XIconifyWindow (*ivdynam_XIconifyWindow)
#undef XWithdrawWindow
#define XWithdrawWindow (*ivdynam_XWithdrawWindow)
#undef XGetCommand
#define XGetCommand (*ivdynam_XGetCommand)
#undef XGetWMColormapWindows
#define XGetWMColormapWindows (*ivdynam_XGetWMColormapWindows)
#undef XSetWMColormapWindows
#define XSetWMColormapWindows (*ivdynam_XSetWMColormapWindows)
#undef XFreeStringList
#define XFreeStringList (*ivdynam_XFreeStringList)
#undef XSetTransientForHint
#define XSetTransientForHint (*ivdynam_XSetTransientForHint)
#undef XActivateScreenSaver
#define XActivateScreenSaver (*ivdynam_XActivateScreenSaver)
#undef XAddHost
#define XAddHost (*ivdynam_XAddHost)
#undef XAddHosts
#define XAddHosts (*ivdynam_XAddHosts)
#undef XAddToExtensionList
#define XAddToExtensionList (*ivdynam_XAddToExtensionList)
#undef XAddToSaveSet
#define XAddToSaveSet (*ivdynam_XAddToSaveSet)
#undef XAllocColor
#define XAllocColor (*ivdynam_XAllocColor)
#undef XAllocColorCells
#define XAllocColorCells (*ivdynam_XAllocColorCells)
#undef XAllocColorPlanes
#define XAllocColorPlanes (*ivdynam_XAllocColorPlanes)
#undef XAllocNamedColor
#define XAllocNamedColor (*ivdynam_XAllocNamedColor)
#undef XAllowEvents
#define XAllowEvents (*ivdynam_XAllowEvents)
#undef XAutoRepeatOff
#define XAutoRepeatOff (*ivdynam_XAutoRepeatOff)
#undef XAutoRepeatOn
#define XAutoRepeatOn (*ivdynam_XAutoRepeatOn)
#undef XBell
#define XBell (*ivdynam_XBell)
#undef XBitmapBitOrder
#define XBitmapBitOrder (*ivdynam_XBitmapBitOrder)
#undef XBitmapPad
#define XBitmapPad (*ivdynam_XBitmapPad)
#undef XBitmapUnit
#define XBitmapUnit (*ivdynam_XBitmapUnit)
#undef XCellsOfScreen
#define XCellsOfScreen (*ivdynam_XCellsOfScreen)
#undef XChangeActivePointerGrab
#define XChangeActivePointerGrab (*ivdynam_XChangeActivePointerGrab)
#undef XChangeGC
#define XChangeGC (*ivdynam_XChangeGC)
#undef XChangeKeyboardControl
#define XChangeKeyboardControl (*ivdynam_XChangeKeyboardControl)
#undef XChangeKeyboardMapping
#define XChangeKeyboardMapping (*ivdynam_XChangeKeyboardMapping)
#undef XChangePointerControl
#define XChangePointerControl (*ivdynam_XChangePointerControl)
#undef XChangeProperty
#define XChangeProperty (*ivdynam_XChangeProperty)
#undef XChangeSaveSet
#define XChangeSaveSet (*ivdynam_XChangeSaveSet)
#undef XChangeWindowAttributes
#define XChangeWindowAttributes (*ivdynam_XChangeWindowAttributes)
#undef XCheckIfEvent
#define XCheckIfEvent (*ivdynam_XCheckIfEvent)
#undef XCheckMaskEvent
#define XCheckMaskEvent (*ivdynam_XCheckMaskEvent)
#undef XCheckTypedEvent
#define XCheckTypedEvent (*ivdynam_XCheckTypedEvent)
#undef XCheckTypedWindowEvent
#define XCheckTypedWindowEvent (*ivdynam_XCheckTypedWindowEvent)
#undef XCheckWindowEvent
#define XCheckWindowEvent (*ivdynam_XCheckWindowEvent)
#undef XCirculateSubwindows
#define XCirculateSubwindows (*ivdynam_XCirculateSubwindows)
#undef XCirculateSubwindowsDown
#define XCirculateSubwindowsDown (*ivdynam_XCirculateSubwindowsDown)
#undef XCirculateSubwindowsUp
#define XCirculateSubwindowsUp (*ivdynam_XCirculateSubwindowsUp)
#undef XClearArea
#define XClearArea (*ivdynam_XClearArea)
#undef XClearWindow
#define XClearWindow (*ivdynam_XClearWindow)
#undef XCloseDisplay
#define XCloseDisplay (*ivdynam_XCloseDisplay)
#undef XConfigureWindow
#define XConfigureWindow (*ivdynam_XConfigureWindow)
#undef XConnectionNumber
#define XConnectionNumber (*ivdynam_XConnectionNumber)
#undef XConvertSelection
#define XConvertSelection (*ivdynam_XConvertSelection)
#undef XCopyArea
#define XCopyArea (*ivdynam_XCopyArea)
#undef XCopyGC
#define XCopyGC (*ivdynam_XCopyGC)
#undef XCopyPlane
#define XCopyPlane (*ivdynam_XCopyPlane)
#undef XDefaultDepth
#define XDefaultDepth (*ivdynam_XDefaultDepth)
#undef XDefaultDepthOfScreen
#define XDefaultDepthOfScreen (*ivdynam_XDefaultDepthOfScreen)
#undef XDefaultScreen
#define XDefaultScreen (*ivdynam_XDefaultScreen)
#undef XDefineCursor
#define XDefineCursor (*ivdynam_XDefineCursor)
#undef XDeleteProperty
#define XDeleteProperty (*ivdynam_XDeleteProperty)
#undef XDestroyWindow
#define XDestroyWindow (*ivdynam_XDestroyWindow)
#undef XDestroySubwindows
#define XDestroySubwindows (*ivdynam_XDestroySubwindows)
#undef XDoesBackingStore
#define XDoesBackingStore (*ivdynam_XDoesBackingStore)
#undef XDoesSaveUnders
#define XDoesSaveUnders (*ivdynam_XDoesSaveUnders)
#undef XDisableAccessControl
#define XDisableAccessControl (*ivdynam_XDisableAccessControl)
#undef XDisplayCells
#define XDisplayCells (*ivdynam_XDisplayCells)
#undef XDisplayHeight
#define XDisplayHeight (*ivdynam_XDisplayHeight)
#undef XDisplayHeightMM
#define XDisplayHeightMM (*ivdynam_XDisplayHeightMM)
#undef XDisplayKeycodes
#define XDisplayKeycodes (*ivdynam_XDisplayKeycodes)
#undef XDisplayPlanes
#define XDisplayPlanes (*ivdynam_XDisplayPlanes)
#undef XDisplayWidth
#define XDisplayWidth (*ivdynam_XDisplayWidth)
#undef XDisplayWidthMM
#define XDisplayWidthMM (*ivdynam_XDisplayWidthMM)
#undef XDrawArc
#define XDrawArc (*ivdynam_XDrawArc)
#undef XDrawArcs
#define XDrawArcs (*ivdynam_XDrawArcs)
#undef XDrawImageString
#define XDrawImageString (*ivdynam_XDrawImageString)
#undef XDrawImageString16
#define XDrawImageString16 (*ivdynam_XDrawImageString16)
#undef XDrawLine
#define XDrawLine (*ivdynam_XDrawLine)
#undef XDrawLines
#define XDrawLines (*ivdynam_XDrawLines)
#undef XDrawPoint
#define XDrawPoint (*ivdynam_XDrawPoint)
#undef XDrawPoints
#define XDrawPoints (*ivdynam_XDrawPoints)
#undef XDrawRectangle
#define XDrawRectangle (*ivdynam_XDrawRectangle)
#undef XDrawRectangles
#define XDrawRectangles (*ivdynam_XDrawRectangles)
#undef XDrawSegments
#define XDrawSegments (*ivdynam_XDrawSegments)
#undef XDrawString
#define XDrawString (*ivdynam_XDrawString)
#undef XDrawString16
#define XDrawString16 (*ivdynam_XDrawString16)
#undef XDrawText
#define XDrawText (*ivdynam_XDrawText)
#undef XDrawText16
#define XDrawText16 (*ivdynam_XDrawText16)
#undef XEnableAccessControl
#define XEnableAccessControl (*ivdynam_XEnableAccessControl)
#undef XEventsQueued
#define XEventsQueued (*ivdynam_XEventsQueued)
#undef XFetchName
#define XFetchName (*ivdynam_XFetchName)
#undef XFillArc
#define XFillArc (*ivdynam_XFillArc)
#undef XFillArcs
#define XFillArcs (*ivdynam_XFillArcs)
#undef XFillPolygon
#define XFillPolygon (*ivdynam_XFillPolygon)
#undef XFillRectangle
#define XFillRectangle (*ivdynam_XFillRectangle)
#undef XFillRectangles
#define XFillRectangles (*ivdynam_XFillRectangles)
#undef XFlush
#define XFlush (*ivdynam_XFlush)
#undef XForceScreenSaver
#define XForceScreenSaver (*ivdynam_XForceScreenSaver)
#undef XFree
#define XFree (*ivdynam_XFree)
#undef XFreeColormap
#define XFreeColormap (*ivdynam_XFreeColormap)
#undef XFreeColors
#define XFreeColors (*ivdynam_XFreeColors)
#undef XFreeCursor
#define XFreeCursor (*ivdynam_XFreeCursor)
#undef XFreeExtensionList
#define XFreeExtensionList (*ivdynam_XFreeExtensionList)
#undef XFreeFont
#define XFreeFont (*ivdynam_XFreeFont)
#undef XFreeFontInfo
#define XFreeFontInfo (*ivdynam_XFreeFontInfo)
#undef XFreeFontNames
#define XFreeFontNames (*ivdynam_XFreeFontNames)
#undef XFreeFontPath
#define XFreeFontPath (*ivdynam_XFreeFontPath)
#undef XFreeGC
#define XFreeGC (*ivdynam_XFreeGC)
#undef XFreeModifiermap
#define XFreeModifiermap (*ivdynam_XFreeModifiermap)
#undef XFreePixmap
#define XFreePixmap (*ivdynam_XFreePixmap)
#undef XGeometry
#define XGeometry (*ivdynam_XGeometry)
#undef XGetErrorDatabaseText
#define XGetErrorDatabaseText (*ivdynam_XGetErrorDatabaseText)
#undef XGetErrorText
#define XGetErrorText (*ivdynam_XGetErrorText)
#undef XGetFontProperty
#define XGetFontProperty (*ivdynam_XGetFontProperty)
#undef XGetGCValues
#define XGetGCValues (*ivdynam_XGetGCValues)
#undef XGetGeometry
#define XGetGeometry (*ivdynam_XGetGeometry)
#undef XGetIconName
#define XGetIconName (*ivdynam_XGetIconName)
#undef XGetInputFocus
#define XGetInputFocus (*ivdynam_XGetInputFocus)
#undef XGetKeyboardControl
#define XGetKeyboardControl (*ivdynam_XGetKeyboardControl)
#undef XGetPointerControl
#define XGetPointerControl (*ivdynam_XGetPointerControl)
#undef XGetPointerMapping
#define XGetPointerMapping (*ivdynam_XGetPointerMapping)
#undef XGetScreenSaver
#define XGetScreenSaver (*ivdynam_XGetScreenSaver)
#undef XGetTransientForHint
#define XGetTransientForHint (*ivdynam_XGetTransientForHint)
#undef XGetWindowProperty
#define XGetWindowProperty (*ivdynam_XGetWindowProperty)
#undef XGetWindowAttributes
#define XGetWindowAttributes (*ivdynam_XGetWindowAttributes)
#undef XGrabButton
#define XGrabButton (*ivdynam_XGrabButton)
#undef XGrabKey
#define XGrabKey (*ivdynam_XGrabKey)
#undef XGrabKeyboard
#define XGrabKeyboard (*ivdynam_XGrabKeyboard)
#undef XGrabPointer
#define XGrabPointer (*ivdynam_XGrabPointer)
#undef XGrabServer
#define XGrabServer (*ivdynam_XGrabServer)
#undef XHeightMMOfScreen
#define XHeightMMOfScreen (*ivdynam_XHeightMMOfScreen)
#undef XHeightOfScreen
#define XHeightOfScreen (*ivdynam_XHeightOfScreen)
#undef XIfEvent
#define XIfEvent (*ivdynam_XIfEvent)
#undef XImageByteOrder
#define XImageByteOrder (*ivdynam_XImageByteOrder)
#undef XInstallColormap
#define XInstallColormap (*ivdynam_XInstallColormap)
#undef XKeysymToKeycode
#define XKeysymToKeycode (*ivdynam_XKeysymToKeycode)
#undef XKillClient
#define XKillClient (*ivdynam_XKillClient)
#undef XLookupColor
#define XLookupColor (*ivdynam_XLookupColor)
#undef XLowerWindow
#define XLowerWindow (*ivdynam_XLowerWindow)
#undef XMapRaised
#define XMapRaised (*ivdynam_XMapRaised)
#undef XMapSubwindows
#define XMapSubwindows (*ivdynam_XMapSubwindows)
#undef XMapWindow
#define XMapWindow (*ivdynam_XMapWindow)
#undef XMaskEvent
#define XMaskEvent (*ivdynam_XMaskEvent)
#undef XMaxCmapsOfScreen
#define XMaxCmapsOfScreen (*ivdynam_XMaxCmapsOfScreen)
#undef XMinCmapsOfScreen
#define XMinCmapsOfScreen (*ivdynam_XMinCmapsOfScreen)
#undef XMoveResizeWindow
#define XMoveResizeWindow (*ivdynam_XMoveResizeWindow)
#undef XMoveWindow
#define XMoveWindow (*ivdynam_XMoveWindow)
#undef XNextEvent
#define XNextEvent (*ivdynam_XNextEvent)
#undef XNoOp
#define XNoOp (*ivdynam_XNoOp)
#undef XParseColor
#define XParseColor (*ivdynam_XParseColor)
#undef XParseGeometry
#define XParseGeometry (*ivdynam_XParseGeometry)
#undef XPeekEvent
#define XPeekEvent (*ivdynam_XPeekEvent)
#undef XPeekIfEvent
#define XPeekIfEvent (*ivdynam_XPeekIfEvent)
#undef XPending
#define XPending (*ivdynam_XPending)
#undef XPlanesOfScreen
#define XPlanesOfScreen (*ivdynam_XPlanesOfScreen)
#undef XProtocolRevision
#define XProtocolRevision (*ivdynam_XProtocolRevision)
#undef XProtocolVersion
#define XProtocolVersion (*ivdynam_XProtocolVersion)
#undef XPutBackEvent
#define XPutBackEvent (*ivdynam_XPutBackEvent)
#undef XPutImage
#define XPutImage (*ivdynam_XPutImage)
#undef XQLength
#define XQLength (*ivdynam_XQLength)
#undef XQueryBestCursor
#define XQueryBestCursor (*ivdynam_XQueryBestCursor)
#undef XQueryBestSize
#define XQueryBestSize (*ivdynam_XQueryBestSize)
#undef XQueryBestStipple
#define XQueryBestStipple (*ivdynam_XQueryBestStipple)
#undef XQueryBestTile
#define XQueryBestTile (*ivdynam_XQueryBestTile)
#undef XQueryColor
#define XQueryColor (*ivdynam_XQueryColor)
#undef XQueryColors
#define XQueryColors (*ivdynam_XQueryColors)
#undef XQueryExtension
#define XQueryExtension (*ivdynam_XQueryExtension)
#undef XQueryKeymap
#define XQueryKeymap (*ivdynam_XQueryKeymap)
#undef XQueryPointer
#define XQueryPointer (*ivdynam_XQueryPointer)
#undef XQueryTextExtents
#define XQueryTextExtents (*ivdynam_XQueryTextExtents)
#undef XQueryTextExtents16
#define XQueryTextExtents16 (*ivdynam_XQueryTextExtents16)
#undef XQueryTree
#define XQueryTree (*ivdynam_XQueryTree)
#undef XRaiseWindow
#define XRaiseWindow (*ivdynam_XRaiseWindow)
#undef XReadBitmapFile
#define XReadBitmapFile (*ivdynam_XReadBitmapFile)
#undef XReadBitmapFileData
#define XReadBitmapFileData (*ivdynam_XReadBitmapFileData)
#undef XRebindKeysym
#define XRebindKeysym (*ivdynam_XRebindKeysym)
#undef XRecolorCursor
#define XRecolorCursor (*ivdynam_XRecolorCursor)
#undef XRefreshKeyboardMapping
#define XRefreshKeyboardMapping (*ivdynam_XRefreshKeyboardMapping)
#undef XRemoveFromSaveSet
#define XRemoveFromSaveSet (*ivdynam_XRemoveFromSaveSet)
#undef XRemoveHost
#define XRemoveHost (*ivdynam_XRemoveHost)
#undef XRemoveHosts
#define XRemoveHosts (*ivdynam_XRemoveHosts)
#undef XReparentWindow
#define XReparentWindow (*ivdynam_XReparentWindow)
#undef XResetScreenSaver
#define XResetScreenSaver (*ivdynam_XResetScreenSaver)
#undef XResizeWindow
#define XResizeWindow (*ivdynam_XResizeWindow)
#undef XRestackWindows
#define XRestackWindows (*ivdynam_XRestackWindows)
#undef XRotateBuffers
#define XRotateBuffers (*ivdynam_XRotateBuffers)
#undef XRotateWindowProperties
#define XRotateWindowProperties (*ivdynam_XRotateWindowProperties)
#undef XScreenCount
#define XScreenCount (*ivdynam_XScreenCount)
#undef XSelectInput
#define XSelectInput (*ivdynam_XSelectInput)
#undef XSendEvent
#define XSendEvent (*ivdynam_XSendEvent)
#undef XSetAccessControl
#define XSetAccessControl (*ivdynam_XSetAccessControl)
#undef XSetArcMode
#define XSetArcMode (*ivdynam_XSetArcMode)
#undef XSetBackground
#define XSetBackground (*ivdynam_XSetBackground)
#undef XSetClipMask
#define XSetClipMask (*ivdynam_XSetClipMask)
#undef XSetClipOrigin
#define XSetClipOrigin (*ivdynam_XSetClipOrigin)
#undef XSetClipRectangles
#define XSetClipRectangles (*ivdynam_XSetClipRectangles)
#undef XSetCloseDownMode
#define XSetCloseDownMode (*ivdynam_XSetCloseDownMode)
#undef XSetCommand
#define XSetCommand (*ivdynam_XSetCommand)
#undef XSetDashes
#define XSetDashes (*ivdynam_XSetDashes)
#undef XSetFillRule
#define XSetFillRule (*ivdynam_XSetFillRule)
#undef XSetFillStyle
#define XSetFillStyle (*ivdynam_XSetFillStyle)
#undef XSetFont
#define XSetFont (*ivdynam_XSetFont)
#undef XSetFontPath
#define XSetFontPath (*ivdynam_XSetFontPath)
#undef XSetForeground
#define XSetForeground (*ivdynam_XSetForeground)
#undef XSetFunction
#define XSetFunction (*ivdynam_XSetFunction)
#undef XSetGraphicsExposures
#define XSetGraphicsExposures (*ivdynam_XSetGraphicsExposures)
#undef XSetIconName
#define XSetIconName (*ivdynam_XSetIconName)
#undef XSetInputFocus
#define XSetInputFocus (*ivdynam_XSetInputFocus)
#undef XSetLineAttributes
#define XSetLineAttributes (*ivdynam_XSetLineAttributes)
#undef XSetModifierMapping
#define XSetModifierMapping (*ivdynam_XSetModifierMapping)
#undef XSetPlaneMask
#define XSetPlaneMask (*ivdynam_XSetPlaneMask)
#undef XSetPointerMapping
#define XSetPointerMapping (*ivdynam_XSetPointerMapping)
#undef XSetScreenSaver
#define XSetScreenSaver (*ivdynam_XSetScreenSaver)
#undef XSetSelectionOwner
#define XSetSelectionOwner (*ivdynam_XSetSelectionOwner)
#undef XSetState
#define XSetState (*ivdynam_XSetState)
#undef XSetStipple
#define XSetStipple (*ivdynam_XSetStipple)
#undef XSetSubwindowMode
#define XSetSubwindowMode (*ivdynam_XSetSubwindowMode)
#undef XSetTSOrigin
#define XSetTSOrigin (*ivdynam_XSetTSOrigin)
#undef XSetTile
#define XSetTile (*ivdynam_XSetTile)
#undef XSetWindowBackground
#define XSetWindowBackground (*ivdynam_XSetWindowBackground)
#undef XSetWindowBackgroundPixmap
#define XSetWindowBackgroundPixmap (*ivdynam_XSetWindowBackgroundPixmap)
#undef XSetWindowBorder
#define XSetWindowBorder (*ivdynam_XSetWindowBorder)
#undef XSetWindowBorderPixmap
#define XSetWindowBorderPixmap (*ivdynam_XSetWindowBorderPixmap)
#undef XSetWindowBorderWidth
#define XSetWindowBorderWidth (*ivdynam_XSetWindowBorderWidth)
#undef XSetWindowColormap
#define XSetWindowColormap (*ivdynam_XSetWindowColormap)
#undef XStoreBuffer
#define XStoreBuffer (*ivdynam_XStoreBuffer)
#undef XStoreBytes
#define XStoreBytes (*ivdynam_XStoreBytes)
#undef XStoreColor
#define XStoreColor (*ivdynam_XStoreColor)
#undef XStoreColors
#define XStoreColors (*ivdynam_XStoreColors)
#undef XStoreName
#define XStoreName (*ivdynam_XStoreName)
#undef XStoreNamedColor
#define XStoreNamedColor (*ivdynam_XStoreNamedColor)
#undef XSync
#define XSync (*ivdynam_XSync)
#undef XTextExtents
#define XTextExtents (*ivdynam_XTextExtents)
#undef XTextExtents16
#define XTextExtents16 (*ivdynam_XTextExtents16)
#undef XTextWidth
#define XTextWidth (*ivdynam_XTextWidth)
#undef XTextWidth16
#define XTextWidth16 (*ivdynam_XTextWidth16)
#undef XTranslateCoordinates
#define XTranslateCoordinates (*ivdynam_XTranslateCoordinates)
#undef XUndefineCursor
#define XUndefineCursor (*ivdynam_XUndefineCursor)
#undef XUngrabButton
#define XUngrabButton (*ivdynam_XUngrabButton)
#undef XUngrabKey
#define XUngrabKey (*ivdynam_XUngrabKey)
#undef XUngrabKeyboard
#define XUngrabKeyboard (*ivdynam_XUngrabKeyboard)
#undef XUngrabPointer
#define XUngrabPointer (*ivdynam_XUngrabPointer)
#undef XUngrabServer
#define XUngrabServer (*ivdynam_XUngrabServer)
#undef XUninstallColormap
#define XUninstallColormap (*ivdynam_XUninstallColormap)
#undef XUnloadFont
#define XUnloadFont (*ivdynam_XUnloadFont)
#undef XUnmapSubwindows
#define XUnmapSubwindows (*ivdynam_XUnmapSubwindows)
#undef XUnmapWindow
#define XUnmapWindow (*ivdynam_XUnmapWindow)
#undef XVendorRelease
#define XVendorRelease (*ivdynam_XVendorRelease)
#undef XWarpPointer
#define XWarpPointer (*ivdynam_XWarpPointer)
#undef XWidthMMOfScreen
#define XWidthMMOfScreen (*ivdynam_XWidthMMOfScreen)
#undef XWidthOfScreen
#define XWidthOfScreen (*ivdynam_XWidthOfScreen)
#undef XWindowEvent
#define XWindowEvent (*ivdynam_XWindowEvent)
#undef XWriteBitmapFile
#define XWriteBitmapFile (*ivdynam_XWriteBitmapFile)
#undef XOpenOM
#define XOpenOM (*ivdynam_XOpenOM)
#undef XCloseOM
#define XCloseOM (*ivdynam_XCloseOM)
#undef XSetOMValues
#define XSetOMValues (*ivdynam_XSetOMValues)
#undef XGetOMValues
#define XGetOMValues (*ivdynam_XGetOMValues)
#undef XDisplayOfOM
#define XDisplayOfOM (*ivdynam_XDisplayOfOM)
#undef XLocaleOfOM
#define XLocaleOfOM (*ivdynam_XLocaleOfOM)
#undef XCreateOC
#define XCreateOC (*ivdynam_XCreateOC)
#undef XDestroyOC
#define XDestroyOC (*ivdynam_XDestroyOC)
#undef XOMOfOC
#define XOMOfOC (*ivdynam_XOMOfOC)
#undef XSetOCValues
#define XSetOCValues (*ivdynam_XSetOCValues)
#undef XGetOCValues
#define XGetOCValues (*ivdynam_XGetOCValues)
#undef XCreateFontSet
#define XCreateFontSet (*ivdynam_XCreateFontSet)
#undef XFreeFontSet
#define XFreeFontSet (*ivdynam_XFreeFontSet)
#undef XFontsOfFontSet
#define XFontsOfFontSet (*ivdynam_XFontsOfFontSet)
#undef XBaseFontNameListOfFontSet
#define XBaseFontNameListOfFontSet (*ivdynam_XBaseFontNameListOfFontSet)
#undef XLocaleOfFontSet
#define XLocaleOfFontSet (*ivdynam_XLocaleOfFontSet)
#undef XContextDependentDrawing
#define XContextDependentDrawing (*ivdynam_XContextDependentDrawing)
#undef XDirectionalDependentDrawing
#define XDirectionalDependentDrawing (*ivdynam_XDirectionalDependentDrawing)
#undef XContextualDrawing
#define XContextualDrawing (*ivdynam_XContextualDrawing)
#undef XExtentsOfFontSet
#define XExtentsOfFontSet (*ivdynam_XExtentsOfFontSet)
#undef XmbTextEscapement
#define XmbTextEscapement (*ivdynam_XmbTextEscapement)
#undef XwcTextEscapement
#define XwcTextEscapement (*ivdynam_XwcTextEscapement)
#undef Xutf8TextEscapement
#define Xutf8TextEscapement (*ivdynam_Xutf8TextEscapement)
#undef XmbTextExtents
#define XmbTextExtents (*ivdynam_XmbTextExtents)
#undef XwcTextExtents
#define XwcTextExtents (*ivdynam_XwcTextExtents)
#undef Xutf8TextExtents
#define Xutf8TextExtents (*ivdynam_Xutf8TextExtents)
#undef XmbTextPerCharExtents
#define XmbTextPerCharExtents (*ivdynam_XmbTextPerCharExtents)
#undef XwcTextPerCharExtents
#define XwcTextPerCharExtents (*ivdynam_XwcTextPerCharExtents)
#undef Xutf8TextPerCharExtents
#define Xutf8TextPerCharExtents (*ivdynam_Xutf8TextPerCharExtents)
#undef XmbDrawText
#define XmbDrawText (*ivdynam_XmbDrawText)
#undef XwcDrawText
#define XwcDrawText (*ivdynam_XwcDrawText)
#undef Xutf8DrawText
#define Xutf8DrawText (*ivdynam_Xutf8DrawText)
#undef XmbDrawString
#define XmbDrawString (*ivdynam_XmbDrawString)
#undef XwcDrawString
#define XwcDrawString (*ivdynam_XwcDrawString)
#undef Xutf8DrawString
#define Xutf8DrawString (*ivdynam_Xutf8DrawString)
#undef XmbDrawImageString
#define XmbDrawImageString (*ivdynam_XmbDrawImageString)
#undef XwcDrawImageString
#define XwcDrawImageString (*ivdynam_XwcDrawImageString)
#undef Xutf8DrawImageString
#define Xutf8DrawImageString (*ivdynam_Xutf8DrawImageString)
#undef XOpenIM
#define XOpenIM (*ivdynam_XOpenIM)
#undef XCloseIM
#define XCloseIM (*ivdynam_XCloseIM)
#undef XGetIMValues
#define XGetIMValues (*ivdynam_XGetIMValues)
#undef XSetIMValues
#define XSetIMValues (*ivdynam_XSetIMValues)
#undef XDisplayOfIM
#define XDisplayOfIM (*ivdynam_XDisplayOfIM)
#undef XLocaleOfIM
#define XLocaleOfIM (*ivdynam_XLocaleOfIM)
#undef XCreateIC
#define XCreateIC (*ivdynam_XCreateIC)
#undef XDestroyIC
#define XDestroyIC (*ivdynam_XDestroyIC)
#undef XSetICFocus
#define XSetICFocus (*ivdynam_XSetICFocus)
#undef XUnsetICFocus
#define XUnsetICFocus (*ivdynam_XUnsetICFocus)
#undef XwcResetIC
#define XwcResetIC (*ivdynam_XwcResetIC)
#undef XmbResetIC
#define XmbResetIC (*ivdynam_XmbResetIC)
#undef Xutf8ResetIC
#define Xutf8ResetIC (*ivdynam_Xutf8ResetIC)
#undef XSetICValues
#define XSetICValues (*ivdynam_XSetICValues)
#undef XGetICValues
#define XGetICValues (*ivdynam_XGetICValues)
#undef XIMOfIC
#define XIMOfIC (*ivdynam_XIMOfIC)
#undef XFilterEvent
#define XFilterEvent (*ivdynam_XFilterEvent)
#undef XmbLookupString
#define XmbLookupString (*ivdynam_XmbLookupString)
#undef XwcLookupString
#define XwcLookupString (*ivdynam_XwcLookupString)
#undef Xutf8LookupString
#define Xutf8LookupString (*ivdynam_Xutf8LookupString)
#undef XVaCreateNestedList
#define XVaCreateNestedList (*ivdynam_XVaCreateNestedList)
#undef XRegisterIMInstantiateCallback
#define XRegisterIMInstantiateCallback (*ivdynam_XRegisterIMInstantiateCallback)
#undef XUnregisterIMInstantiateCallback
#define XUnregisterIMInstantiateCallback (*ivdynam_XUnregisterIMInstantiateCallback)
#undef XInternalConnectionNumbers
#define XInternalConnectionNumbers (*ivdynam_XInternalConnectionNumbers)
#undef XProcessInternalConnection
#define XProcessInternalConnection (*ivdynam_XProcessInternalConnection)
#undef XAddConnectionWatch
#define XAddConnectionWatch (*ivdynam_XAddConnectionWatch)
#undef XRemoveConnectionWatch
#define XRemoveConnectionWatch (*ivdynam_XRemoveConnectionWatch)
#undef XSetAuthorization
#define XSetAuthorization (*ivdynam_XSetAuthorization)
#undef _Xmbtowc
#define _Xmbtowc (*ivdynam__Xmbtowc)
#undef _Xwctomb
#define _Xwctomb (*ivdynam__Xwctomb)
#undef XGetEventData
#define XGetEventData (*ivdynam_XGetEventData)
#undef XFreeEventData
#define XFreeEventData (*ivdynam_XFreeEventData)
#undef XDestroyImage
#define XDestroyImage (*ivdynam_XDestroyImage)
#undef XGetPixel
#define XGetPixel (*ivdynam_XGetPixel)
#undef XPutPixel
#define XPutPixel (*ivdynam_XPutPixel)
#undef XSubImage
#define XSubImage (*ivdynam_XSubImage)
#undef XAddPixel
#define XAddPixel (*ivdynam_XAddPixel)
#undef XAllocClassHint
#define XAllocClassHint (*ivdynam_XAllocClassHint)
#undef XAllocIconSize
#define XAllocIconSize (*ivdynam_XAllocIconSize)
#undef XAllocSizeHints
#define XAllocSizeHints (*ivdynam_XAllocSizeHints)
#undef XAllocStandardColormap
#define XAllocStandardColormap (*ivdynam_XAllocStandardColormap)
#undef XAllocWMHints
#define XAllocWMHints (*ivdynam_XAllocWMHints)
#undef XClipBox
#define XClipBox (*ivdynam_XClipBox)
#undef XCreateRegion
#define XCreateRegion (*ivdynam_XCreateRegion)
#undef XDestroyRegion
#define XDestroyRegion (*ivdynam_XDestroyRegion)
#undef XEmptyRegion
#define XEmptyRegion (*ivdynam_XEmptyRegion)
#undef XEqualRegion
#define XEqualRegion (*ivdynam_XEqualRegion)
#undef XFindContext
#define XFindContext (*ivdynam_XFindContext)
#undef XGetClassHint
#define XGetClassHint (*ivdynam_XGetClassHint)
#undef XGetIconSizes
#define XGetIconSizes (*ivdynam_XGetIconSizes)
#undef XGetNormalHints
#define XGetNormalHints (*ivdynam_XGetNormalHints)
#undef XGetRGBColormaps
#define XGetRGBColormaps (*ivdynam_XGetRGBColormaps)
#undef XGetSizeHints
#define XGetSizeHints (*ivdynam_XGetSizeHints)
#undef XGetStandardColormap
#define XGetStandardColormap (*ivdynam_XGetStandardColormap)
#undef XGetTextProperty
#define XGetTextProperty (*ivdynam_XGetTextProperty)
#undef XGetVisualInfo
#define XGetVisualInfo (*ivdynam_XGetVisualInfo)
#undef XGetWMClientMachine
#define XGetWMClientMachine (*ivdynam_XGetWMClientMachine)
#undef XGetWMHints
#define XGetWMHints (*ivdynam_XGetWMHints)
#undef XGetWMIconName
#define XGetWMIconName (*ivdynam_XGetWMIconName)
#undef XGetWMName
#define XGetWMName (*ivdynam_XGetWMName)
#undef XGetWMNormalHints
#define XGetWMNormalHints (*ivdynam_XGetWMNormalHints)
#undef XGetWMSizeHints
#define XGetWMSizeHints (*ivdynam_XGetWMSizeHints)
#undef XGetZoomHints
#define XGetZoomHints (*ivdynam_XGetZoomHints)
#undef XIntersectRegion
#define XIntersectRegion (*ivdynam_XIntersectRegion)
#undef XConvertCase
#define XConvertCase (*ivdynam_XConvertCase)
#undef XLookupString
#define XLookupString (*ivdynam_XLookupString)
#undef XMatchVisualInfo
#define XMatchVisualInfo (*ivdynam_XMatchVisualInfo)
#undef XOffsetRegion
#define XOffsetRegion (*ivdynam_XOffsetRegion)
#undef XPointInRegion
#define XPointInRegion (*ivdynam_XPointInRegion)
#undef XPolygonRegion
#define XPolygonRegion (*ivdynam_XPolygonRegion)
#undef XRectInRegion
#define XRectInRegion (*ivdynam_XRectInRegion)
#undef XSaveContext
#define XSaveContext (*ivdynam_XSaveContext)
#undef XSetClassHint
#define XSetClassHint (*ivdynam_XSetClassHint)
#undef XSetIconSizes
#define XSetIconSizes (*ivdynam_XSetIconSizes)
#undef XSetNormalHints
#define XSetNormalHints (*ivdynam_XSetNormalHints)
#undef XSetRGBColormaps
#define XSetRGBColormaps (*ivdynam_XSetRGBColormaps)
#undef XSetSizeHints
#define XSetSizeHints (*ivdynam_XSetSizeHints)
#undef XSetStandardProperties
#define XSetStandardProperties (*ivdynam_XSetStandardProperties)
#undef XSetTextProperty
#define XSetTextProperty (*ivdynam_XSetTextProperty)
#undef XSetWMClientMachine
#define XSetWMClientMachine (*ivdynam_XSetWMClientMachine)
#undef XSetWMHints
#define XSetWMHints (*ivdynam_XSetWMHints)
#undef XSetWMIconName
#define XSetWMIconName (*ivdynam_XSetWMIconName)
#undef XSetWMName
#define XSetWMName (*ivdynam_XSetWMName)
#undef XSetWMNormalHints
#define XSetWMNormalHints (*ivdynam_XSetWMNormalHints)
#undef XSetWMProperties
#define XSetWMProperties (*ivdynam_XSetWMProperties)
#undef XmbSetWMProperties
#define XmbSetWMProperties (*ivdynam_XmbSetWMProperties)
#undef Xutf8SetWMProperties
#define Xutf8SetWMProperties (*ivdynam_Xutf8SetWMProperties)
#undef XSetWMSizeHints
#define XSetWMSizeHints (*ivdynam_XSetWMSizeHints)
#undef XSetRegion
#define XSetRegion (*ivdynam_XSetRegion)
#undef XSetStandardColormap
#define XSetStandardColormap (*ivdynam_XSetStandardColormap)
#undef XSetZoomHints
#define XSetZoomHints (*ivdynam_XSetZoomHints)
#undef XShrinkRegion
#define XShrinkRegion (*ivdynam_XShrinkRegion)
#undef XStringListToTextProperty
#define XStringListToTextProperty (*ivdynam_XStringListToTextProperty)
#undef XSubtractRegion
#define XSubtractRegion (*ivdynam_XSubtractRegion)
#undef XmbTextListToTextProperty
#define XmbTextListToTextProperty (*ivdynam_XmbTextListToTextProperty)
#undef XwcTextListToTextProperty
#define XwcTextListToTextProperty (*ivdynam_XwcTextListToTextProperty)
#undef Xutf8TextListToTextProperty
#define Xutf8TextListToTextProperty (*ivdynam_Xutf8TextListToTextProperty)
#undef XwcFreeStringList
#define XwcFreeStringList (*ivdynam_XwcFreeStringList)
#undef XTextPropertyToStringList
#define XTextPropertyToStringList (*ivdynam_XTextPropertyToStringList)
#undef XmbTextPropertyToTextList
#define XmbTextPropertyToTextList (*ivdynam_XmbTextPropertyToTextList)
#undef XwcTextPropertyToTextList
#define XwcTextPropertyToTextList (*ivdynam_XwcTextPropertyToTextList)
#undef Xutf8TextPropertyToTextList
#define Xutf8TextPropertyToTextList (*ivdynam_Xutf8TextPropertyToTextList)
#undef XUnionRectWithRegion
#define XUnionRectWithRegion (*ivdynam_XUnionRectWithRegion)
#undef XUnionRegion
#define XUnionRegion (*ivdynam_XUnionRegion)
#undef XWMGeometry
#define XWMGeometry (*ivdynam_XWMGeometry)
#undef XXorRegion
#define XXorRegion (*ivdynam_XXorRegion)

#endif
